= Factory Building Stats

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

API Endpoint: getFactory +
Factory Stats +

*ADVISORY:* Due to performance, all factory calls use a caching system. Therefore, you will not always get the most up-to-date info on your factory. Please consult the Configuration page to set caching delays.

getAssembler only retrieves Assemblers +
getBlender only retrieves Blenders +
getConstructor only retrieves Constructors +
getParticle only retrieves Particle Accelerators +
etc... +

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|building
|Type of Factory Building
|String
|Output

|location/x
|X Location of Building
|Float
|Output

|location/y
|Y Location of Building
|Float
|Output

|location/z
|Z Location of Building
|Float
|Output

|location/Rotation
|Compass Heading of Building
|Float
|Output

|Recipe
|Item to be Produced
|String
|Output

|production/Name
|Item Output
|String Array
|Output

|production/CurrentProd
|Current Production
|Float Array
|Output

|production/MaxProd
|Max Production
|Float Array
|Output

|production/ProdPercent
|Efficentcy Percentage
|Float Array
|Output

|production/Inventory
|Number of items stored in Building for item
|Integar Array
|Output

|ingredients/Name
|Item Output
|String Array
|Output

|ingredients/CurrentConsumed
|Current Consumption
|Float Array
|Output

|ingredients/MaxConsumed
|Max Consumption
|Float Array
|Output

|ingredients/ConsPercent
|Efficentcy Percentage
|Float Array
|Output

|ingredients/Inventory
|Number of items stored in Building for item
|Integar Array
|Output

|ManuSpeed
|Configured Speed
|Float
|Output

|IsConfigured
|Is a recipe configured?
|Boolean
|Output

|IsProducing
|Is the building producing now?
|Boolean
|Output

|IsPaused
|Is paused?
|Boolean
|Output

|CircuitID
|Circuit ID of the Building
|Integar
|Output

|===

Example:
[source,json]
-----------------
[{
      "building":"Refinery",
      "location":{
         "x":-83587.078125,"y":-170347.1875,"z":-1710.079102,
         "rotation":190
      },
      "Recipe":"Fuel",
      "production":[
         {
            "Name":"Fuel",
            "CurrentProd":37176.5,
            "MaxProd":40000.0,
            "ProdPercent":92.900002,
            "Inventory":10
         },
         {
            "Name":"Polymer Resin",
            "CurrentProd":27.9,
            "MaxProd":30.0,
            "ProdPercent":92.900002,
            "Inventory":23
         }
      ],
      "ingredients":[
         {
            "Name":"Crude Oil",
            "CurrentConsumed":55764.699219,
            "MaxConsumed":60000.0,
            "ConsPercent":92.900002,
            "Inventory":120
         }
      ],
      "ManuSpeed":1.0,
      "IsConfigured":true,
      "IsProducing":true,
      "IsPaused":false,
      "CircuitID": 28
}, 
{
      "building":"Assembler",
      "location":{
         "x":-92857.976562,"y":-128723.0,"z":-210.157852,
         "rotation":-80
      },
      "Recipe":"Reinforced Iron Plate",
      "production":[
         {
            "Name":"Reinforced Iron Plate",
            "CurrentProd":5.0,
            "MaxProd":5.0,
            "ProdPercent":100.0,
            "Inventory":3
         }
      ],
      "ingredients":[
         {
            "Name":"Iron Plate",
            "CurrentConsumed":30.0,
            "MaxConsumed":30.0,
            "ConsPercent":100.0,
            "Inventory":50
         },
         {
            "Name":"Screw",
            "CurrentConsumed":60.0,
            "MaxConsumed":60.0,
            "ConsPercent":100.0,
            "Inventory":500
         }
      ],
      "ManuSpeed":1.0,
      "IsConfigured":true,
      "IsProducing":true,
      "IsPaused":false,
      "CircuitID": 44
}]
-----------------