= Vehicles Stats

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

API Endpoint: getVehicles +
Vehicles Stats +

getExplorer only retrieves Explorers +
getTractor only retrieves Tractors +
getTruck only retrieves Trucks +

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|ID
|UE Asset Name
|String
|Output


|Name
|Name of vehicle type
|String
|Output

|ClassName
|UE Class Name
|String
|Output

|location/x
|X Location of Vehicle
|Float
|Output

|location/y
|Y Location of Vehicle
|Float
|Output

|location/z
|Z Location of Vehicle
|Float
|Output

|location/Rotation
|Compass Heading of Vehicle
|Float
|Output

|ForwardSpeed
|Float in kph
|String
|Output

|CurrentGear
|Transmission Gear
|String
|Output

|EngineRPM
|RPM of Engine
|Integer
|Output

|Airborne
|Is the truck making a jump
|Boolean
|Output

|AutoPilot
|Auto pilot engaged?
|Boolean
|Output

|Storage/Name
|Name
|String
|Output

|Storage/ClassName
|UE Class Name
|String
|Output

|Storage/Amount
|Amount of items
|Integar
|Output

|Fuel/Name
|Name
|String
|Output

|Fuel/ClassName
|UE Class Name
|String
|Output

|Fuel/Amount
|Amount of items
|Integar
|Output

|features/properties/name
|Type of name being marked (Player, Train Track(WIP), Notable Building, etc)
|String
|Output

|features/properties/type
|Type of item being marked (Player, Train Track(WIP), Notable Building, etc)
|String
|Output

|features/geometry/name
|GeoJSON name of map marking (Point, Line, Circle, etc)
|String
|Output

|features/geometry/coordinates
|X,Y,Z for map marking
|[Float, Float, Float]
|Output

|features/geometry/type
|GeoJSON type of map marking (Point, Line, Circle, etc)
|String
|Output

|===

Example:
[source,json]
-----------------
[
  {
    "ID": 0,
    "VehicleType": "Explorer",
    "location":
    {
      "x": -52341.4375,
      "y": -162543.21875,
      "z": -904.133544921875,
      "rotation": 313
    },
    "ForwardSpeed": 0,
    "CurrentGear": 0,
    "EngineRPM": 0,
    "Airborne": false,
    "AutoPilot": false,
    "Storage": [
      {
        "Name": "Battery",
        "ClassName": "Desc_Battery_C",
        "Amount": 200
      },
      {
        "Name": "Battery",
        "ClassName": "Desc_Battery_C",
        "Amount": 200
      }
    ],
    "Fuel": [
      {
        "Name": "Battery",
        "ClassName": "Desc_Battery_C",
        "Amount": 199
      }
    ],
    "ThrottlePercent": 0,
    "PathName": "",
    "FollowingPath": false,
    "features":
    {
      "properties":
      {
        "name": "Explorer",
        "type": "Explorer"
      },
      "geometry":
      {
        "coordinates":
        {
          "X": -52341.4375,
          "Y": -162543.21875,
          "Z": -904.133544921875
        },
        "type": "Point"
      }
    }
  }
]
-----------------