= Vehicles Stats

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

URI Handler: getVehicles +
Vehicles Stats +

getExplorer only retrieves Explorers +
getTractor only retrieves Tractors +
getTruck only retrieves Trucks +

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|ID
|ID number of Vehicle
|Integer
|Output

|VehicleType
|Name of vehicle type
|String
|Output

|location/x
|X Location of Vehicle
|Float
|Output

|location/y
|Y Location of Vehicle
|Float
|Output

|location/z
|Z Location of Vehicle
|Float
|Output

|location/Rotation
|Compass Heading of Vehicle
|Float
|Output

|ForwardSpeed
|Float in kph
|String
|Output

|CurrentGear
|Transmission Gear
|String
|Output

|EngineRPM
|RPM of Engine
|Integer
|Output

|Airborne
|Is the truck making a jump
|Boolean
|Output

|AutoPilot
|Auto pilot engaged?
|Boolean
|Output

|FuelType
|Fuel Type
|String
|Output

|FuelInventory
|Fuel remaining
|Integer
|Output

|===

Example:
[source,json]
-----------------
[{
      "ID":"0",
      "VehicleType":"Explorer",
      "location":{
         "x":-52341.4375,"y":-162543.21875,"z":-904.135193,
         "rotation":313
      },
      "ForwardSpeed":0.0,
      "CurrentGear":0,
      "EngineRPM":0.0,
      "Airborne":false,
      "AutoPilot":false,
      "FuelType":"Battery",
      "FuelInventory":199,
      "ThrottlePercent":0.0,
      "PathName":"",
      "FollowingPath": false,
      "FuelUsed":"",
    "features": {
		"properties":
			{"type": "Explorer"},
		"geometry": {
			"coordinates": {
				"x":-52341.4375,"y":-162543.21875,"z":-904.135193
			},
			"type": "Point"
		}
	}	
}]
-----------------