= Serial/COM/RS-232
Darth Porisius
:url-repo: https://github.com/porisius/FicsitRemoteMonitoring

**This mod's Serial functionality is only expected to be supported on Windows due to the third-party library's compatibility.** That is not to say that this will not work on Mac or Linux, but I cannot confirm. If you would like to test and let me know and how it is done, I will be glad to update this to reflect as well as provide credit.

** Changes to come in this area in U5, ability to call more data similiar to the Web groups.

Communications with a Serial Port requires either a virtual Serial driver or physical hardware. Any serial device (Arduino/RPi/PLC) should work, it will be the code on the device that may need to be customized to match. Examples will be provided in my GitHub (https://www.github.com/porisius/FicsitRemoteMonitoring) and is open for anyone wanting to provide their update/config.

FRM serial communication can be configured on a serial port of your choosing (Default: COM3). This can be modified by either modifying the COM_Port value in %SatisfactoryRootFolder%\FactoryGame\Configs\FicsitRemoteMonitoring.cfg (Config File Method), or by Satisfactory's Main Menu > Mods > FicsitRemoteMonitoring > Serial Port (Game UI Method).

The serial driver, by default, is not activated until the appropriate chat command is provided. You may also have the serial driver auto-start by enabling the Autostart Serial Port in Game UI Method, or changing the COM_Autostart in the Config File Method to true.

Chat Commands:

/frmserial start - Starts the serial driver +
/frmserial stop - Stops the serial driver

Data from Serial is in JSON and presented as a string, but their true data types are listed in the table. Input/Output is from the perspective of the FRM mod. Output, FRM sends data. Input, FRM listens for data.

Please note that there are no nested JSONs. The table below are only grouped for easy lookup. List to be expanded upon feedback and able.

You may have FRM auto-send getPowerData to you every delay per the settings in the FRM config.

You may also have your own delay on your serial device and send URI handlers to FRM to get an output. URIs may be sent manually or programmicly, but require a "copy/paste" approach. +
Developer's Note: Tests show that all the data is sent, however, my terminal program only shows 4KB of data regardless of attempts. More information is required.