= Ficsit Remote Management
Darth Porisius
:url-repo: https://www.github.com/porisius/RS232_SF_Project

**Mod is not yet released, finishing final touches (as well as this guide) before beta version.**

**Mod only works in SML 3.1.0 and above due to changes in SML**

**This mod's Serial functionality is only expected to be supported on Windows due to the third-party library's compatibility.** That is not to say that this will not work on Mac or Linux, but I cannot confirm. If you would like to test and let me know and how it is done, I will be glad to update this to reflect as well as provide credit.

Communications with a Serial Port requires either a virtual Serial driver or physical hardware. Any serial device (Arduino/RPi/PLC) should work, it will be the code on the device that may need to be customized to match. Examples will be provided in my GitHub (https://github.com/porisius/RS232_SF_Project) and is open for anyone wanting to provide their update/config.

**WebSockets is a WIP function. I am not sure when it will be implemented, don't ask for an ETA.**
WebSockets functionality uses the Socket.IO client to communicate with a server. You will need a server-side application to receive the data, and then display it in a manner either as a .Net application or web server. **Websockets is NOT my specialty, so please don't ask me.** I am, hopefully, providing the ability to allow the mod to be more flexible. If you want to contribute, I will add it to the mod and provide credit.

Data from Websockets or Serial is in JSON and read as a string, but their true data types are listed in the table. Input/Output is from the perspective of the FRM mod. Output, FRM sends data. Input, FRM listens for data.

Please note that there are no nested JSONs. The table below are only grouped in  for easy lookup. List to be expanded upon feedback and able.

[cols="1,1,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

4+|*Power Monitoring:*

|PowerConsumed
|Power consumed on selected power circuit
|Float
|Output

|PowerCapacity
|Power capacity on selected power circuit
|Float
|Output
	
|PowerMaxConsumed
|Maximum Power that can be consumed on selected power circuit
|Float
|Output
	
|BatteryDifferential
|Amount of power in excess/deficit going into or out of the battery bank(s). Positive = Charges batteries, Negative = Drains batteries
|Float
|Output
	
|BatteryPercent
|Percentage of battery bank(s) charge
|Float
|Output
	
|BatteryCapacity
|Total capacity of battery bank(s)
|Float
|Output
	
|BatteryTimeEmpty
|Time (in seconds "needs confirmed") until Batteries are empty
|Float
|Output
|===
|===
4+|**Power Management: NOT YET IMPLEMENTED**
	
|FuseBlown
|Is the fuse blown for selected circuit
|Boolean (true/false)
|Output
	
|ResetFuse
|Command received to reset blown fuse
|Boolean (true/false)
|Input
	
|===