import {
  CLASSNAMED_PATH,
  ITEMS_PATH,
  MARKERS_PATH,
  MONOCHROMEICONS_PATH,
  STAMPS_PATH,
  UTILS_PATH,
} from "@/public/map/paths";

export const images = {
  Artifacts: {
    Mercer_Sphere: `${CLASSNAMED_PATH}BP_WAT2_C.avif`,
    Somersloop: `${CLASSNAMED_PATH}BP_WAT1_C.avif`,
  },
  Buildings: {
    Build_Pipeline_MK1: `${CLASSNAMED_PATH}Build_Pipeline_C.avif`,
    Conveyor_Belt_MK1: `${CLASSNAMED_PATH}Build_ConveyorBeltMk1_C.avif`,
    Desc_GeneratorCoal_C: `${CLASSNAMED_PATH}Desc_GeneratorCoal_C.avif`,
    Desc_MinerMk3_C: `${CLASSNAMED_PATH}Desc_MinerMk3_C.avif`,
    Desc_PipeHyper_C: `${CLASSNAMED_PATH}Desc_PipeHyper_C.avif`,
  },
  Creatures: {
    Space_Rabbit: `${CLASSNAMED_PATH}Char_SpaceRabbit_C.avif`, // Doggo, Lizard Doggo
  },
  Empty:
    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=",
  Items: {
    Power_Shard: `${ITEMS_PATH}/Power_Shard.avif`,
  },
  Markers: {
    Beacon: `${MARKERS_PATH}beacon.avif`,
    Crate_Death: `${MARKERS_PATH}crate_death.avif`,
    Crate_Loot: `${MARKERS_PATH}crate_loot.avif`,
    Drone: `${MARKERS_PATH}drone.avif`,
    Drone_Station: `${MARKERS_PATH}drone_station.avif`,
    Drop_Pod: `${MARKERS_PATH}drop_pod.avif`,
    Explorer: `${MARKERS_PATH}explorer.avif`,
    Factory_Cart: `${MARKERS_PATH}factory_cart.avif`,
    Hub: `${MARKERS_PATH}hub.avif`,
    Player: `${MARKERS_PATH}player.avif`,
    Player_Dead: `${MARKERS_PATH}player_dead.avif`,
    Player_Offline: `${MARKERS_PATH}player_offline.avif`,
    Portal: `${MARKERS_PATH}portal.avif`,
    Portal_Satellite: `${MARKERS_PATH}portal_satellite.avif`,
    Power: `${MARKERS_PATH}power.avif`,
    Question_Mark: `${MARKERS_PATH}question_mark.avif`,
    Radar_Tower: `${MARKERS_PATH}radar_tower.avif`,
    Radiation: `${MARKERS_PATH}radiation.avif`,
    Recycle: `${MARKERS_PATH}recycle.avif`,
    Space_Elevator: `${MARKERS_PATH}space_elevator.avif`,
    Tape: `${MARKERS_PATH}tape.avif`,
    Tractor: `${MARKERS_PATH}tractor.avif`,
    Train: `${MARKERS_PATH}train.avif`,
    Train_Station: `${MARKERS_PATH}train_station.avif`,
    Truck: `${MARKERS_PATH}truck.avif`,
    Truck_Station: `${MARKERS_PATH}truck_station.avif`,
    Vehicle_Receive: `${MARKERS_PATH}vehicle_receive.avif`,
    Vehicle_Sending: `${MARKERS_PATH}vehicle_sending.avif`,
  },
  MonochromeIcons: {
    Aggro: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Aggro.avif`,
    Arrow_Down: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Arrow_Down.avif`,
    Arrow_DownLeft: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Arrow_DownLeft.avif`,
    Arrow_DownRight: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Arrow_DownRight.avif`,
    Arrow_Left: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Arrow_Left.avif`,
    Arrow_Right: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Arrow_Right.avif`,
    Arrow_Up: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Arrow_Up.avif`,
    Arrow_UpLeft: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Arrow_UpLeft.avif`,
    Arrow_UpRight: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Arrow_UpRight.avif`,
    Check: `${MONOCHROMEICONS_PATH}TXUI_IndicatorPanel_Check.avif`,
    Cogwheel: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Cogwheel.avif`,
    Crate: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Crate.avif`,
    Drone: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Drone.avif`,
    Drop: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Drop.avif`,
    Exit: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Exit.avif`,
    Exlamation_Mark: `${MONOCHROMEICONS_PATH}TXUI_MIcon_ExlamationMark.avif`,
    Explorer: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Explorer.avif`,
    Factory: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Factory.avif`,
    Factory_Cart: `${MONOCHROMEICONS_PATH}TXUI_MIcon_FactoryCart.avif`,
    Home: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Home.avif`,
    Loop: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Loop.avif`,
    Next: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Next.avif`,
    Pause: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Pause.avif`,
    Pioneer: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Pioneer.avif`,
    Play: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Play.avif`,
    Portal: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Portal.avif`,
    Portal_Satellite: `${MONOCHROMEICONS_PATH}TXUI_MIcon_PortalSatellite.avif`,
    Power: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Power.avif`,
    Previous: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Previous.avif`,
    Question_Mark: `${MONOCHROMEICONS_PATH}TXUI_MIcon_QuestionMark.avif`,
    Radiation: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Radiation.avif`,
    Recycle: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Recycle.avif`,
    Resize_Width: `${MONOCHROMEICONS_PATH}TXUI_MIcon_ResizeWidth.avif`,
    RoadArrow_Down: `${MONOCHROMEICONS_PATH}TXUI_MIcon_RoadArrow_Down.avif`,
    RoadArrow_TurnAround: `${MONOCHROMEICONS_PATH}TXUI_MIcon_RoadArrow_TurnAround.avif`,
    RoadArrow_TurnLeft: `${MONOCHROMEICONS_PATH}TXUI_MIcon_RoadArrow_TurnLeft.avif`,
    RoadArrow_TurnRight: `${MONOCHROMEICONS_PATH}TXUI_MIcon_RoadArrow_TurnRight.avif`,
    RoadArrow_Up: `${MONOCHROMEICONS_PATH}TXUI_MIcon_RoadArrow_Up.avif`,
    Small_Tape: `${MONOCHROMEICONS_PATH}TXUI_MIcon_SmallTape.avif`,
    SortRule_Any: `${MONOCHROMEICONS_PATH}TXUI_MIcon_SortRule_Any.avif`,
    SortRule_AnyUndefined: `${MONOCHROMEICONS_PATH}TXUI_MIcon_SortRule_AnyUndefined.avif`,
    SortRule_Overflow: `${MONOCHROMEICONS_PATH}TXUI_MIcon_SortRule_Overflow.avif`,
    Speedometer: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Speedometer.avif`,
    Stop_X: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Stop_X.avif`,
    ThumbDown: `${MONOCHROMEICONS_PATH}TXUI_MIcon_ThumbDown.avif`,
    ThumbUp: `${MONOCHROMEICONS_PATH}TXUI_MIcon_ThumbUp.avif`,
    Tractor: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Tractor.avif`,
    Train: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Train.avif`,
    Trash: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Trash.avif`,
    Truck: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Truck.avif`,
    VolDown: `${MONOCHROMEICONS_PATH}TXUI_MIcon_VolDown.avif`,
    VolUp: `${MONOCHROMEICONS_PATH}TXUI_MIcon_VolUp.avif`,
    Warning: `${MONOCHROMEICONS_PATH}TXUI_MIcon_Warning.avif`,
  },
  Patterns: {
    PatternDesc_Icon_Factory_C: `${CLASSNAMED_PATH}PatternDesc_Icon_Factory_C.avif`,
  },
  Slugs: {
    MK1: `${CLASSNAMED_PATH}BP_Crystal_C.avif`,
    MK2: `${CLASSNAMED_PATH}BP_Crystal_mk2_C.avif`,
    MK3: `${CLASSNAMED_PATH}BP_Crystal_mk3_C.avif`,
  },
  Stamps: {
    Biomass: `${STAMPS_PATH}TXUI_Biomass_Map.avif`,
    Cave: `${STAMPS_PATH}TXUI_Cave_Map.avif`,
    Crash: `${STAMPS_PATH}TXUI_Crash_Map.avif`,
    Crate: `${STAMPS_PATH}TXUI_Crate_Map.avif`,
    Creature: `${STAMPS_PATH}TXUI_Creature_Map.avif`,
    Fluids: `${STAMPS_PATH}TXUI_Fluids_Map.avif`,
    Fruit: `${STAMPS_PATH}TXUI_Berries_Map.avif`,
    Mark: `${STAMPS_PATH}TXUI_EMark_Map.avif`,
    "Question Mark": `${STAMPS_PATH}TXUI_QMark_Map.avif`,
    Radiation: `${STAMPS_PATH}TXUI_Radiation_Map.avif`,
    Rock: `${STAMPS_PATH}TXUI_Rock_Map.avif`,
    Slug: `${STAMPS_PATH}TXUI_Slug_Map.avif`,
    Warning: `${STAMPS_PATH}TXUI_Warning_Map.avif`,
  },
  Utils: {
    Lock: `${UTILS_PATH}lock.avif`,
    Rotation: `${UTILS_PATH}rotation.avif`,
  },
};
