= Belt Stats/GeoLocation

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

API Endpoint: getBelts +

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|Name
|Belt Type
|String
|Output

|ClassName
|UE Class Name
|String
|Output

|ItemName
|Items on Belt (Future Function)
|String
|Output

|location0/x
|X Location of Belt
|Float
|Output

|location0/y
|Y Location of Belt
|Float
|Output

|location0/z
|Z Location of Belt
|Float
|Output

|Connected0
|Is Belt Connected at starting point?
|Boolean
|Output

|location1/x
|X Location of Belt
|Float
|Output

|location1/y
|Y Location of Belt
|Float
|Output

|location1/z
|Z Location of Belt
|Float
|Output

|Connected1
|Is Belt Connected at starting point?
|Boolean
|Output

|Speed
|Belt Speed
|Integer
|Output

|features/properties/name
|Type of name being marked (Player, Train Track(WIP), Notable Building, etc)
|String
|Output

|features/properties/type
|Type of item being marked (Player, Train Track(WIP), Notable Building, etc)
|String
|Output

|features/geometry/name
|GeoJSON name of map marking (Point, Line, Circle, etc)
|String
|Output

|features/geometry/coordinates
|X,Y,Z for map marking
|[Float, Float, Float]
|Output

|features/geometry/type
|GeoJSON type of map marking (Point, Line, Circle, etc)
|String
|Output

|===

Example:
[source,json]
-----------------
[	
   {
      "Name": "Conveyor Belt Mk.1",
      "ClassName": "Build_ConveyorBeltMk1_C_89",
      "location0":
      {
         "X": -104125.7109375,
         "Y": -133350.21875,
         "Z": -1310.15771484375
      },
      "Connected0": true,
      "location1":
      {
         "X": -104015.5859375,
         "Y": -132823.078125,
         "Z": -1310.1578369140625
      },
      "Connected1": true,
      "Speed": 120,
      "features":
      {
         "properties":
         {
            "name": "Conveyor Belt Mk.1",
            "type": "Conveyor Belt Mk.1"
         },
         "geometry":
         {
            "coordinates": [
               {
                  "X": -104125.7109375,
                  "Y": -133350.21875,
                  "Z": -1310.15771484375
               },
               {
                  "X": -104015.5859375,
                  "Y": -132823.078125,
                  "Z": -1310.1578369140625
               }
            ],
            "type": "Line"
         }
      }
   }
]
-----------------