= Drop Pod/Crash Site

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

API Endpoint: getDropPod + 

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|ID
|DropPod ID
|String
|Output

|location/x
|X Location of DropPod
|Float
|Output

|location/y
|Y Location of DropPod
|Float
|Output

|location/z
|Z Location of DropPod
|Float
|Output

|location/Rotation
|Compass Heading of DropPod
|Float
|Output

|Looted
|Has Hard Drive been collected?
|Boolean
|Output

|RepairItem
|Item Required to Repair DropPod
|String
|Output

|RepairItemClass
|UE Class Name
|String
|Output

|RepairAmount
|# of Repair Item required to open DropPod/Crash Site
|Integer
|Output

|PowerRequired
|Power Required to open DropPod/Crash Site
|Float
|Output

|features/properties/name
|Type of name being marked (Player, Train Track(WIP), Notable Building, etc)
|String
|Output

|features/properties/type
|Type of item being marked (Player, Train Track(WIP), Notable Building, etc)
|String
|Output

|features/geometry/name
|GeoJSON name of map marking (Point, Line, Circle, etc)
|String
|Output

|features/geometry/coordinates
|X,Y,Z for map marking
|[Float, Float, Float]
|Output

|features/geometry/type
|GeoJSON type of map marking (Point, Line, Circle, etc)
|String
|Output

|===

Example:
[source,json]
-----------------
[
   {
      "DropPodID": 0,
      "location":
      {
         "X": -123677.3671875,
         "Y": -167107.46875,
         "Z": 29710.71875
      },
      "Looted": true,
      "RepairItem": "Motor",
      "RepairItemClass": "Desc_Motor_C",
      "RepairAmount": 4,
      "PowerRequired": 0,
      "features":
      {
         "properties":
         {
            "name": "Crash Site #0",
            "type": "Drop Pod"
         },
         "geometry":
         {
            "coordinates":
            {
               "X": -123677.3671875,
               "Y": -167107.46875,
               "Z": 29710.71875
            },
            "type": "Point"
         }
      }
   },
   {
      "DropPodID": 1,
      "location":
      {
         "X": 236508.34375,
         "Y": -312236.40625,
         "Z": 9971.1552734375
      },
      "Looted": true,
      "RepairItem": "Motor",
      "RepairItemClass": "Desc_Motor_C",
      "RepairAmount": 30,
      "PowerRequired": 0,
      "features":
      {
         "properties":
         {
            "name": "Crash Site #1",
            "type": "Drop Pod"
         },
         "geometry":
         {
            "coordinates":
            {
               "X": 236508.34375,
               "Y": -312236.40625,
               "Z": 9971.1552734375
            },
            "type": "Point"
         }
      }
   }
]
-----------------