= Lizard Doggo Info

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

API Endpoint: getDoggo +

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|ID
|Doggo ID
|Integer
|Output

|Name
|Doggo Name
|String
|Output

|ClassName
|UE Class Name
|String
|Output

|location/x
|X Location of Lizard Doggo
|Float
|Output

|location/y
|Y Location of Lizard Doggo
|Float
|Output

|location/z
|Z Location of Lizard Doggo
|Float
|Output

|location/Rotation
|Compass Heading of Lizard Doggo
|Float
|Output

|ItemName
|Item in Doggo's Inventory
|String
|Output

|ClassName
|UE Class Name
|String
|Output

|ItemAmt
|# of Item in Doggo's Inventory
|Integer
|Output

|MapArea
|Map Area Name (Future Feature)
|String
|Output

|features/properties/name
|Type of name being marked (Player, Train Track(WIP), Notable Building, etc)
|String
|Output

|features/properties/type
|Type of item being marked (Player, Train Track(WIP), Notable Building, etc)
|String
|Output

|features/geometry/name
|GeoJSON name of map marking (Point, Line, Circle, etc)
|String
|Output

|features/geometry/coordinates
|X,Y,Z for map marking
|[Float, Float, Float]
|Output

|features/geometry/type
|GeoJSON type of map marking (Point, Line, Circle, etc)
|String
|Output

|===

Example:
[source,json]
-----------------
[
      {
            "ID": 0,
            "Name": "DoggoWithLongName",
            "ClassName": "Char_SpaceRabbit_C_2147364440",
            "location":
            {
                  "x": -94763.59375,
                  "y": -119329.2578125,
                  "z": -1139.87548828125,
                  "rotation": 178
            },
            "Inventory": [
                  {
                        "Name": "Purple Power Slug",
                        "ClassName": "Desc_Crystal_mk3_C",
                        "Amount": 1
                  }
            ],
            "MapArea": ""
      },
      {
            "ID": 1,
            "Name": "DoggoWithLongName",
            "ClassName": "Char_SpaceRabbit_C_2146938592",
            "location":
            {
                  "x": -94779.3671875,
                  "y": -119239.90625,
                  "z": -1139.7823486328125,
                  "rotation": 150
            },
            "Inventory": [
                  {
                        "Name": "Wood",
                        "ClassName": "Desc_Wood_C",
                        "Amount": 4
                  }
            ],
            "MapArea": ""
      }
]
-----------------