= Drone Stats

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

API Endpoint: getDrone +

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|ID
|ID Number of Drone
|Integer
|Output

|VehicleType
|Drone Name
|String
|Output

|ClassName
|UE Class Name
|String
|Output

|location/x
|X Location of Drone
|Float
|Output

|location/y
|Y Location of Drone
|Float
|Output

|location/z
|Z Location of Drone
|Float
|Output

|location/Rotation
|Compass Heading of Drone
|Float
|Output

|HomeStation
|Drone's Home Station
|String
|Output

|CurrentDestination
|Current Destination Drone Station
|String
|Output

|FlyingSpeed
|Flying Speed of Drone
|Integer
|Output

|CurrentFlyingMode
|Current ENUM Status
|String
|Output

|features/properties/name
|Type of name being marked (Player, Train Track(WIP), Notable Building, etc)
|String
|Output

|features/properties/type
|Type of item being marked (Player, Train Track(WIP), Notable Building, etc)
|String
|Output

|features/geometry/name
|GeoJSON name of map marking (Point, Line, Circle, etc)
|String
|Output

|features/geometry/coordinates
|X,Y,Z for map marking
|[Float, Float, Float]
|Output

|features/geometry/type
|GeoJSON type of map marking (Point, Line, Circle, etc)
|String
|Output

|===

Example:
[source,json]
-----------------
[
  {
    "ID": 0,
    "Name": "Drone",
    "ClassName": "BP_DroneTransport_C_2147138365",
    "location":
    {
      "x": -56065.14453125,
      "y": -156554.703125,
      "z": 1550.282958984375,
      "rotation": 10
    },
    "CurrentDestination": "Storage Import 2",
    "HomeStation": "Aluminium Drone",
    "FlyingSpeed": 0,
    "CurrentFlyingMode": 5.0609362990541046e+18,
    "features":
    {
      "properties":
      {
        "name": "Drone",
        "type": "Drone"
      },
      "geometry":
      {
        "coordinates":
        {
          "X": -56065.14453125,
          "Y": -156554.703125,
          "Z": 1550.282958984375
        },
        "type": "Point"
      }
    }
  },
  {
    "ID": 1,
    "Name": "Drone",
    "ClassName": "BP_DroneTransport_C_2147201133",
    "location":
    {
      "x": -81024.140625,
      "y": -146122.15625,
      "z": 3992.3212890625,
      "rotation": 255
    },
    "CurrentDestination": "Battery Import",
    "HomeStation": "Battery Port",
    "FlyingSpeed": 130.0966796875,
    "CurrentFlyingMode": 5.0609362990541046e+18,
    "features":
    {
      "properties":
      {
        "name": "Drone",
        "type": "Drone"
      },
      "geometry":
      {
        "coordinates":
        {
          "X": -81024.140625,
          "Y": -146122.15625,
          "Z": 3992.3212890625
        },
        "type": "Point"
      }
    }
  }
]
-----------------