= Drone Stats

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

API Endpoint: getDrone +

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|ID
|ID Number of Drone
|Integer
|Output

|VehicleType
|Drone Name
|String
|Output

|location/x
|X Location of Drone
|Float
|Output

|location/y
|Y Location of Drone
|Float
|Output

|location/z
|Z Location of Drone
|Float
|Output

|location/Rotation
|Compass Heading of Drone
|Float
|Output

|HomeStation
|Drone's Home Station
|String
|Output

|CurrentDestination
|Current Destination Drone Station
|String
|Output

|FlyingSpeed
|Flying Speed of Drone
|Integer
|Output

|CurrentFlyingMode
|Current ENUM Status
|String
|Output

|features/properties/type
|Type of item being marked (Player, Train Track(WIP), Notable Building, etc)
|String
|Output

|features/geometry/type
|GeoJSON type of map marking (Point, Line, Circle, etc)
|String
|Output

|features/geometry/coordinates
|X,Y,Z for map marking
|[Float, Float, Float]
|Output

|===

Example:
[source,json]
-----------------
[{
      "ID":"0",
      "VehicleType":"Drone",
      "location":{
         "x":-101315.90625,"y":-123853.492188,"z":3984.685059,
         "rotation":47
      },
      "HomeStation":"BlameFeatheredToast",
      "CurrentDestination":"",
      "FlyingSpeed":1000,
      "CurrentFlyingMode":"DFM_Travel",
    "features": {
		"properties":
			{"type": "Drone"},
		"geometry": {
			"coordinates": {
					"x":-101315.90625,"y":-123853.492188,"z":3984.685059			},
			"type": "Point"
		}
	}
},{
      "ID":"1",
      "VehicleType":"Drone",
      "location":{
         "x":-60792.097656,"y":-157388.921875,"z":1549.842285,
         "rotation":10
      },
      "CurrentDestination":"",
      "FlyingSpeed":1000,
      "CurrentFlyingMode":"DFM_None",
    "features": {
		"properties":
			{"type": "Drone"},
		"geometry": {
			"coordinates": {
					"x":-60792.097656,"y":-157388.921875,"z":1549.842285			},
			"type": "Point"
		}
	}
}]
-----------------