= Drone Stats

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

URI Handler: getDroneStation +

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|ID
|ID Number
|String
|Output

|HomeStation
|Drone Station
|String
|Output

|location/x
|X Location of Drone Station
|Float
|Output

|location/y
|Y Location of Drone Station
|Float
|Output

|location/z
|Z Location of Drone Station
|Float
|Output

|location/Rotation
|Compass Heading of Drone Station
|Float
|Output

|Paired Station
|Drone Station paired to Home Station
|String
|Output

|Drone Status
|Drone flight status (Taking off, loading/unloading, En route, etc) Note that any drones that are queued to land are described as En Route.
|String
|Output

|AvgIncRate
|Average Incoming Rate
|Float
|Output

|AvgIncStack
|Average Incoming Stack Rate
|Float
|Output

|AvgOutRate
|Average Outgoing Rate
|Float
|Output

|AvgOutStack
|Average Outgoing Stack Rate
|Float
|Output

|AvgRngTrip
|Average Round Trip Time
|String
|Output

|AvgTotalIncRate
|Average Total Incoming Rate
|Float
|Output

|AvgTotalIncStack
|Average Total Incoming Stack
|Float
|Output

|AvgTotalOutRate
|Average Total Outgoing Rate
|Float
|Output

|AvgTotalOutStack
|Average Total Outgoing Stack
|Float
|Output

|AvgTripIncAmt
|Average Trip Incoming Amount
|Float
|Output

|EstRndTrip
|Estimated Round Trip Time
|String
|Output

|EstTotalTransRate
|Estimated Total Transfer Rate
|Float
|Output

|EstLatestTotalIncStack
|Estimated Latest Total Incoming Stack Rate
|Float
|Output

|EstLatestTotalOutStack
|Estimated Latest Total Outgoing Stack Rate
|Float
|Output

|LatestIncStack
|Latest Incoming Item Stack Rate
|Float
|Output

|LatestOutStack
|Latest Outgoing Item Stack Rate
|Float
|Output

|LatestRndTrip
|Latest Round Trip Time
|String
|Output

|LatestTripIncAmt
|Latest Trip Incoming Item Amount
|Integer
|Output

|LatestTripOutAmt
|Latest Trip Outgoing Item Amount
|Integer
|Output

|MedianRndTrip
|Median Round Trip Time
|String
|Output

|MedianTripIncAmt
|Median Trip Incoming Item Amount
|Float
|Output

|MedianTripOutAmt
|Median Trip Outgoing Item Amount
|Float
|Output

|EstBatteryRate
|Estimated Battery Requirement Rate
|Float
|Output

|===

Example:
[source,json]
-----------------
[{
    "ID":"0",
    "HomeStation":"Aluminium Drone",
    "location":{
		"x":-102771.085938,"y":-85182.867188,"z":2589.842285,
        "rotation":"90"
    },
    "PairedStation":"Storage Import 2",
    "DroneStatus":"EDS_TAKEOFF",
    "AvgIncRate":0.0,
	"AvgIncStack":0.0,
	"AvgOutRate":217.800003,
	"AvgOutStack":1.2,
	"AvgRndTrip":"00:02:54",
	"AvgTotalIncRate":0.0,
	"AvgTotalIncStack":0.0,
	"AvgTotalOutRate":217.800003,
	"AvgTotalOutStack":1.2,
	"AvgTripIncAmt":0.0,
	"EstRndTrip":"00:02:10",
	"EstTotalTransRate":4.1,
	"EstTransRate":4.1,
	"EstLatestTotalIncStack":0.0,
	"EstLatestTotalOutStack":1.2,
	"LatestIncStack":0.0,
	"LatestOutStack":1.2,
	"LatestRndTrip":"00:02:54",
	"LatestTripIncAmt":0,
	"LatestTripOutAmt":634,
	"MedianRndTrip":"00:02:54",
	"MedianTripIncAmt":0.0,
	"MedianTripOutAmt":634.0,
	"EstBatteryRate":2.8,
    "features": {
		"properties":
			{"type": "Drone Station"},
		"geometry": {
			"coordinates": {
					"x":-102771.085938,"y":-85182.867188,"z":2589.842285
			},
			"type": "Point"
		}
	}	
},{
    "ID":"1",
    "HomeStation":"Battery Port",
    "location":{
		"x":-105134.585938,"y":-85599.773438,"z":2589.842285,
        "rotation":"90"
    },
    "PairedStation":"Battery Import",
    "DroneStatus":"EDS_EN_ROUTE",
    "AvgIncRate":0.0,
	"AvgIncStack":0.0,
	"AvgOutRate":59.700001,
	"AvgOutStack":0.3,
	"AvgRndTrip":"00:02:52",
	"AvgTotalIncRate":0.0,
	"AvgTotalIncStack":0.0,
	"AvgTotalOutRate":59.700001,
	"AvgTotalOutStack":0.3,
	"AvgTripIncAmt":0.0,
	"EstRndTrip":"00:02:10",
	"EstTotalTransRate":4.1,
	"EstTransRate":4.1,
	"EstLatestTotalIncStack":0.0,
	"EstLatestTotalOutStack":0.3,
	"LatestIncStack":0.0,
	"LatestOutStack":0.3,
	"LatestRndTrip":"00:02:52",
	"LatestTripIncAmt":0,
	"LatestTripOutAmt":172,
	"MedianRndTrip":"00:02:52",
	"MedianTripIncAmt":0.0,
	"MedianTripOutAmt":172.0,
	"EstBatteryRate":2.8,
    "features": {
		"properties":
			{"type": "Drone Station"},
		"geometry": {
			"coordinates": {
					"x":-105134.585938,"y":-85599.773438,"z":2589.842285
			},
			"type": "Point"
		}
	}	
}]
-----------------