:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring
:depth:

= Get Drone Station

include::../_isGetAll.adoc[]

Gets a list of all drone stations.

== URL

`GET http://localhost:8080/getDroneStation`

include::../_responseBody.adoc[]

| ID | String | Unique ID of the Drone Station.
| Name | String | Name of the Drone Station.
| ClassName | String | ClassName of the Drone Station.

{set:key-name:location}
{set:key-description:Location details of the Drone.}
include::../Models/_location.adoc[]

{set:inventory-name:InputInventory}
{set:inventory-description:List of items in the input inventory.}
include::../Models/_inventoryItem.adoc[]

{set:inventory-name:OutputInventory}
{set:inventory-description:List of items in the output inventory.}
include::../Models/_inventoryItem.adoc[]

{set:inventory-name:FuelInventory}
{set:inventory-description:List of items in the fuel inventory.}
include::../Models/_inventoryItem.adoc[]

| PairedStation | String | Station name of the paired Station (None if not set).
| DroneStatus | String | TODO + 
`Unknown`: Status is unknown. +
`Cannot Unload`: Unable to unload the drone. +
`Docked`: Drone is docked. +
`Docking`: Drone is in the process of docking. +
`En Route`: Drone is on its way. +
`Loading`: Items are being loaded into the drone. +
`Not Enough Fuel`: Insufficient fuel at the drone station. +
`No Drone`: Drone station is missing a drone. +
`Taking Off`: Drone is taking off. +
`Unloading`: Items are being unloaded from the drone.

| AvgIncRate | Float | The average amount of incoming items transferred per minute based on previous trips.
| AvgIncStack | Float | The average amount of incoming item stacks transferred per minute based on previous trips.
| AvgOutRate | Float | The average amount of outgoing items transferred per minute based on previous trips.
| AvgOutStack | Float | The average number of item stacks this station sends away per minute, including connected stations.
| AvgRndTrip | String | The average round-trip time of the drone attached to this station based on the last few trips. Format: Hours:Minutes:Seconds
| AvgTotalIncRate | Float | The average number of items this station receives per minute, including connected stations.
| AvgTotalIncStack | Float | The average number of item stacks this station receives per minute, including connected stations.
| AvgTotalOutRate | Float | The average number of items this station sends away per minute, including connected stations.
| AvgTotalOutStack | Float | The average number of item stacks this station sends away per minute, including connected stations.
| AvgTripIncAmt | Float | The average trip incoming item amount of the drone attached to this station.
| AvgTripOutAmt | Float | The average trip outgoing item amount of the drone attached to this station.
| EstTotalTransRate | Float | The estimated number of stacks this station can send away / receive per minute, including drones from connected stations.
| EstLatestTotalIncStack | Float | The number of stacks this station receives per minute, including connected stations, using the most recent trip for each station if available, otherwise uses estimate.
| EstLatestTotalOutStack | Float | The number of stacks this station sends away per minute, including connected stations, using the most recent trip for each station if available, otherwise uses estimate.
| LatestIncStack | Float | The latest trip's amount of incoming item stacks transferred per minute.
| LatestOutStack | Float | The latest trip's amount of outgoing item stacks transferred per minute.
| LatestRndTrip | Float | The latest round-trip time of the drone attached to this station.
| LatestTripIncAmt | Integer | The latest trip incoming item amount of the drone attached to this station.
| LatestTripOutAmt | Integer | The latest trip outgoing item amount of the drone attached to this station.
| MedianRndTrip | String | Median time for a round trip. Format: Hours:Minutes:Seconds
| MedianTripIncAmt | Float | The median trip incoming item amount of the drone attached to this station.
| MedianTripOutAmt | Float | The median trip outgoing item amount of the drone attached to this station.

| ActiveFuel | Object | Current Fuel Information
| {depth}  FuelName | Integer | Name of the Fuel.
| {depth}  SingleTripFuelCost | Float | Required fuel for a single round trip
| {depth}  EstimatedTransportRate | Float | Roughly how many items per minute can be delivered with this fuel type.
| {depth}  EstimatedRoundTripTime | Float | Roughly how long time a single trip will take in seconds.
| {depth}  EstimatedFuelCostRate | Float | Roughly how many items need to be supplied per minute in order for the drone to not have to ever wait for fuel. The actual cost will be lower than this.

| FuelInfo | Object[] | Possible fuel information
| {depth}  FuelName | Integer | Name of the Fuel.
| {depth}  SingleTripFuelCost | Float | Required fuel for a single round trip
| {depth}  EstimatedTransportRate | Float | Roughly how many items per minute can be delivered with this fuel type.
| {depth}  EstimatedRoundTripTime | Float | Roughly how long time a single trip will take in seconds.
| {depth}  EstimatedFuelCostRate | Float | Roughly how many items need to be supplied per minute in order for the drone to not have to ever wait for fuel. The actual cost will be lower than this.

// power info fields
include::../Models/_powerInfo.adoc[]

// features
include::../Models/_features.adoc[]

|===

== Example Response
[source,json]
-----------------
[
  {
    "ID": "Build_DroneStation_C_2147447255",
    "Name": "Arlanda",
    "ClassName": "Build_DroneStation_C",
    "location": {
      "x": -48777.9609375,
      "y": 252677.703125,
      "z": -3760.923583984375,
      "rotation": 90
    },
    "InputInventory": [
      {
        "Name": "Steel Beam",
        "ClassName": "Desc_SteelPlate_C",
        "Amount": 1000,
        "MaxAmount": 200
      }
    ],
    "OutputInventory": [
      {
        "Name": "Steel Beam",
        "ClassName": "Desc_SteelPlate_C",
        "Amount": 200,
        "MaxAmount": 200
      }
    ],
    "FuelInventory": [
      {
        "Name": "Packaged Rocket Fuel",
        "ClassName": "Desc_PackagedRocketFuel_C",
        "Amount": 41,
        "MaxAmount": 100
      }
    ],
    "PairedStation": "Viared",
    "DroneStatus": "Taking Off",
    "AvgIncRate": 0,
    "AvgIncStack": 0,
    "AvgOutRate": 0,
    "AvgOutStack": 0,
    "AvgRndTrip": "00:02:08",
    "AvgTotalIncRate": 0,
    "AvgTotalIncStack": 0,
    "AvgTotalOutRate": 0,
    "AvgTotalOutStack": 0,
    "AvgTripIncAmt": 0,
    "AvgTripOutAmt": 0,
    "EstTotalTransRate": 4.6048984527587891,
    "EstLatestTotalIncStack": 0,
    "EstLatestTotalOutStack": 0,
    "LatestIncStack": 0,
    "LatestOutStack": 0,
    "LatestRndTrip": 128.78955078125,
    "LatestTripIncAmt": 0,
    "LatestTripOutAmt": 0,
    "MedianRndTrip": "00:02:08",
    "MedianTripIncAmt": 0,
    "MedianTripOutAmt": 0,
    "ActiveFuel": {
      "FuelName": "Packaged Rocket Fuel",
      "SingleTripFuelCost": 3.5450289249420166,
      "EstimatedTransportRate": 4.6048984527587891,
      "EstimatedRoundTripTime": 117.26643371582031,
      "EstimatedFuelCostRate": 1.8138331174850464
    },
    "FuelInfo": [
      {
        "FuelName": "Battery",
        "SingleTripFuelCost": 4.2540349960327148,
        "EstimatedTransportRate": 4.7606377601623535,
        "EstimatedRoundTripTime": 113.43017578125,
        "EstimatedFuelCostRate": 2.2502133846282959
      },
      {
        "FuelName": "Packaged Fuel",
        "SingleTripFuelCost": 34.032279968261719,
        "EstimatedTransportRate": 4.5322823524475098,
        "EstimatedRoundTripTime": 119.145263671875,
        "EstimatedFuelCostRate": 17.138212203979492
      },
      {
        "FuelName": "Packaged Turbofuel",
        "SingleTripFuelCost": 12.762104034423828,
        "EstimatedTransportRate": 4.5683021545410156,
        "EstimatedRoundTripTime": 118.20584869384766,
        "EstimatedFuelCostRate": 6.4779047966003418
      },
      {
        "FuelName": "Packaged Rocket Fuel",
        "SingleTripFuelCost": 3.5450289249420166,
        "EstimatedTransportRate": 4.6048984527587891,
        "EstimatedRoundTripTime": 117.26643371582031,
        "EstimatedFuelCostRate": 1.8138331174850464
      },
      {
        "FuelName": "Packaged Ionized Fuel",
        "SingleTripFuelCost": 2.5524208545684814,
        "EstimatedTransportRate": 4.6420855522155762,
        "EstimatedRoundTripTime": 116.3270263671875,
        "EstimatedFuelCostRate": 1.3165062665939331
      },
      {
        "FuelName": "Uranium Fuel Rod",
        "SingleTripFuelCost": 0.034032277762889862,
        "EstimatedTransportRate": 4.6296229362487793,
        "EstimatedRoundTripTime": 116.64016723632812,
        "EstimatedFuelCostRate": 0.017506290227174759
      },
      {
        "FuelName": "Plutonium Fuel Rod",
        "SingleTripFuelCost": 0.017016138881444931,
        "EstimatedTransportRate": 4.6420855522155762,
        "EstimatedRoundTripTime": 116.3270263671875,
        "EstimatedFuelCostRate": 0.0087767085060477257
      }
    ],
    "features": {
      "properties": {
        "name": "Drone Port",
        "type": "Drone Station"
      },
      "geometry": {
        "coordinates": {
          "x": -48777.9609375,
          "y": 252677.703125,
          "z": -3760.923583984375
        },
        "type": "Point"
      }
    },
    "PowerInfo": {
      "CircuitGroupID": 5,
      "CircuitID": 7,
      "PowerConsumed": 100,
      "MaxPowerConsumed": 100
    }
  }
]
-----------------