= Drone Stats

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

API Endpoint: getDroneStation +

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|Name
|Drone Station
|String
|Output

|ClassName
|UE Class Name
|String
|Output

|location/x
|X Location of Drone Station
|Float
|Output

|location/y
|Y Location of Drone Station
|Float
|Output

|location/z
|Z Location of Drone Station
|Float
|Output

|location/Rotation
|Compass Heading of Drone Station
|Float
|Output

|Paired Station
|Drone Station paired to Home Station
|String
|Output

|ConnectedStations
|Connected Drone Stations
|String
|Output

|Drone Status
|Drone flight status (Taking off, loading/unloading, En route, etc) Note that any drones that are queued to land are described as En Route.
|String
|Output

|AvgIncRate
|Average Incoming Rate
|Float
|Output

|AvgIncStack
|Average Incoming Stack Rate
|Float
|Output

|AvgOutRate
|Average Outgoing Rate
|Float
|Output

|AvgOutStack
|Average Outgoing Stack Rate
|Float
|Output

|AvgRngTrip
|Average Round Trip Time
|String
|Output

|AvgTotalIncRate
|Average Total Incoming Rate
|Float
|Output

|AvgTotalIncStack
|Average Total Incoming Stack
|Float
|Output

|AvgTotalOutRate
|Average Total Outgoing Rate
|Float
|Output

|AvgTotalOutStack
|Average Total Outgoing Stack
|Float
|Output

|AvgTripIncAmt
|Average Trip Incoming Amount
|Float
|Output

|EstRndTrip
|Estimated Round Trip Time
|String
|Output

|EstTotalTransRate
|Estimated Total Transfer Rate
|Float
|Output

|EstLatestTotalIncStack
|Estimated Latest Total Incoming Stack Rate
|Float
|Output

|EstLatestTotalOutStack
|Estimated Latest Total Outgoing Stack Rate
|Float
|Output

|LatestIncStack
|Latest Incoming Item Stack Rate
|Float
|Output

|LatestOutStack
|Latest Outgoing Item Stack Rate
|Float
|Output

|LatestRndTrip
|Latest Round Trip Time
|String
|Output

|LatestTripIncAmt
|Latest Trip Incoming Item Amount
|Integer
|Output

|LatestTripOutAmt
|Latest Trip Outgoing Item Amount
|Integer
|Output

|MedianRndTrip
|Median Round Trip Time
|String
|Output

|MedianTripIncAmt
|Median Trip Incoming Item Amount
|Float
|Output

|MedianTripOutAmt
|Median Trip Outgoing Item Amount
|Float
|Output

|EstBatteryRate
|Estimated Battery Requirement Rate
|Float
|Output

|===

Example:
[source,json]
-----------------
[
	{
		"ID": 0,
		"Name": "Drone Port",
		"ClassName": "Build_DroneStation_C_2147259439",
		"location":
		{
			"x": -102771.0859375,
			"y": -85182.8671875,
			"z": 2589.84228515625,
			"rotation": 10
		},
		"PairedStation": "Storage Import 2",
		"DroneStatus": 3,
		"AvgIncRate": 0,
		"AvgIncStack": 0,
		"AvgOutRate": 73.087936401367188,
		"AvgOutStack": 0.47748488187789917,
		"AvgRndTrip": "00:02:54",
		"AvgTotalIncRate": 0,
		"AvgTotalIncStack": 0,
		"AvgTotalOutRate": 73.087936401367188,
		"AvgTotalOutStack": 0.47748488187789917,
		"AvgTripIncAmt": 0,
		"EstRndTrip": "00:02:10",
		"EstTotalTransRate": 4.1415610313415527,
		"EstTransRate": 4.1415610313415527,
		"EstLatestTotalIncStack": 0,
		"EstLatestTotalOutStack": 0.47748488187789917,
		"LatestIncStack": 0,
		"LatestOutStack": 0.47748488187789917,
		"LatestRndTrip": "00:02:54",
		"LatestTripIncAmt": 0,
		"LatestTripOutAmt": 212,
		"MedianRndTrip": "00:02:54",
		"MedianTripIncAmt": 0,
		"MedianTripOutAmt": 212,
		"EstBatteryRate": 2.7610406875610352,
		"features":
		{
			"properties":
			{
				"name": "Drone Port",
				"type": "Drone Station"
			},
			"geometry":
			{
				"coordinates":
				{
					"X": -102771.0859375,
					"Y": -85182.8671875,
					"Z": 2589.84228515625
				},
				"type": "Point"
			}
		}
	},
	{
		"ID": 1,
		"Name": "Drone Port",
		"ClassName": "Build_DroneStation_C_2147256765",
		"location":
		{
			"x": -105134.5859375,
			"y": -85599.7734375,
			"z": 2589.84228515625,
			"rotation": 10
		},
		"PairedStation": "Battery Import",
		"DroneStatus": 4,
		"AvgIncRate": 0,
		"AvgIncStack": 0,
		"AvgOutRate": 33.709449768066406,
		"AvgOutStack": 0.16854724287986755,
		"AvgRndTrip": "00:02:52",
		"AvgTotalIncRate": 0,
		"AvgTotalIncStack": 0,
		"AvgTotalOutRate": 33.709449768066406,
		"AvgTotalOutStack": 0.16854724287986755,
		"AvgTripIncAmt": 0,
		"EstRndTrip": "00:02:10",
		"EstTotalTransRate": 4.1497898101806641,
		"EstTransRate": 4.1497898101806641,
		"EstLatestTotalIncStack": 0,
		"EstLatestTotalOutStack": 0.16854724287986755,
		"LatestIncStack": 0,
		"LatestOutStack": 0.16854724287986755,
		"LatestRndTrip": "00:02:52",
		"LatestTripIncAmt": 0,
		"LatestTripOutAmt": 97,
		"MedianRndTrip": "00:02:52",
		"MedianTripIncAmt": 0,
		"MedianTripOutAmt": 97,
		"EstBatteryRate": 2.766526460647583,
		"features":
		{
			"properties":
			{
				"name": "Drone Port",
				"type": "Drone Station"
			},
			"geometry":
			{
				"coordinates":
				{
					"X": -105134.5859375,
					"Y": -85599.7734375,
					"Z": 2589.84228515625
				},
				"type": "Point"
			}
		}
	}
]
-----------------