= Resource Extractor Stats

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

API Endpoint: getExtractor +

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|building
|Type of Extractor Building
|String
|Output

|location/x
|X Location of Extractor
|Float
|Output

|location/y
|Y Location of Extractor
|Float
|Output

|location/z
|Z Location of Extractor
|Float
|Output

|location/Rotation
|Compass Heading of Extractor
|Float
|Output

|Recipe
|Item to be Produced
|String
|Output

|production/Name
|Item Output
|String Array
|Output

|production/CurrentProd
|Current Production
|Float Array
|Output

|production/MaxProd
|Max Production
|Float Array
|Output

|production/ProdPercent
|Efficentcy Percentage
|Float Array
|Output

|Purity
|Purity of extraction node
|String
|Output

|ManuSpeed
|Configured Speed
|Float
|Output

|IsConfigured
|Is Extractor configured?
|Boolean
|Output

|IsProducing
|Is extracting now?
|Boolean
|Output

|IsPaused
|Is paused?
|Boolean
|Output

|CircuitID
|Circuit ID of the Extractor
|Integar
|Output

|===

Example:
[source,json]
-----------------
[{
      "building":"Oil Extractor",
      "location":{
         "x":-36415.085938,"y":-199979.984375,"z":2486.057617,
         "rotation":150
      },
      "Recipe":"Crude Oil",
      "production":[
         {
            "Name":"Crude Oil",
            "CurrentProd":294.100006,
            "MaxProd":750.0,
            "ProdPercent":"39.200001"
         }
      ],
      "Purity": "Pure"
      "ManuSpeed":2.5,
      "IsConfigured":true,
      "IsProducing":true,
      "IsPaused":false,
      "CircuitID":44
}, {
      "building":"Miner Mk.2",
      "location":{
         "x":-110109.101562,"y":-129159.960938,"z":-1213.412354,
         "rotation":10
      },
      "Recipe":"Coal",
      "production":[
         {
            "Name":"Coal",
            "CurrentProd":119.300003,
            "MaxProd":270.0,
            "ProdPercent":"44.200001"
         }
      ],
      "ManuSpeed":1.5,
      "IsConfigured":true,
      "IsProducing":true,
      "IsPaused":false,
      "CircuitID":44
}]
-----------------