= Power Generation Stats

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

API Endpoint: getGenerators +
Power Generation Stats +

getBiomassGenerator only retrieves Biomass Generators +
getCoalGenerator only retrieves Coal Generators +
getFuelGenerator only retrieves Fuel Generators +
getNuclearGenerator only retrieves Nuclear Power Plants +
getGeothermalGenerator only retrieves Geothermal Generator +

include::../_responseBody.adoc[]

| ID | String | Unique ID of the Factory Building.
| Name | String | Name of the Factory Building.
| ClassName | String | ClassName of the Factory Building.

// location fields
{set:key-name:location}
{set:key-description:Location details of the Factory Building.}
include::../Models/_location.adoc[]

| CircuitID | Integer | Connected Circuit Number
| BaseProd | Float | Base Power Production
| DynamicProdCapacity | Float | Production Capacity
| DynamicProdDemandFactor | Float | Production Demand Factor
| RegulatedDemandProd | Float | Regulated Production
| IsFullBlast | Boolean | Generator Running at Full Blast
| CanStart | Boolean | Can Generator Start
| ProdPowerComsumption | Float | Produced Power being Consumed
| CurrentPotential | Float | Speed Potential (Power Slug)
| ProductionCapacity | Float | Production Capacity
| DefaultProductionCapacity | Float | Default Production Capacity
| PowerProductionPotential | Float | Max Current Power Potential
| FuelAmount | Float | Fuel Inventory

| Supplement | Object | Supplemental Fuel Object
| {depth}  Name | String | Supplement Resource Used (usually water)
| {depth}  ClassName | String | UE Class Name
| {depth}  CurrentConsumed | Float | Rate of Supplement Consumption
| {depth}  MaxConsumed | Float | Max Rate of Supplement Consumption
| {depth}  PercentFull | Float | Inventory Used of Supplement Storage (in %)

| FuelResource | Float | Fuel Type in Inventory
| NuclearWarning | String | Nuclear Power System Alarm (Nuclear Reactors Only)
| GeoMinPower | Float | Minimium Power Generated (Geothermal Generators Only)
| GeoMaxPower | Float | Maximium Power Generated (Geothermal Generators Only)

| AvailableFuel | Object | Available Fuel Object
| {depth}  Name | String | Acceptable Fuel
| {depth}  ClassName | String | UE Class Name
| {depth}  EnergyValue | String | Energy Value of Fuel Used in calculations (MW for Potential / (Energy Value Adjusted by Form) * 60)

| WasteInventory | Object | Waste Inventory Object
| {depth}  Name | String | Nuclear Waste Inventory
| {depth}  ClassName | String | UE Class Name
| {depth}  Amount | Integer | Amount of Waste in Generator

// bounding box
{set:key-name:BoundingBox}
include::../Models/_boundingBox.adoc[]

// features fields
include::../Models/_features.adoc[]
|===

Example:
[source,json]
-----------------
[
   {
      "ID": 0,
      "Name": "Coal Generator",
      "ClassName": "Build_GeneratorCoal_C_32",
      "location":
      {
         "X": -98814.7578125,
         "Y": -143888.078125,
         "Z": -808.1903076171875
      },
      "CircuitID": 44,
      "BaseProd": 0,
      "DynamicProdCapacity": 75,
      "DynamicProdDemandFactor": 1,
      "RegulatedDemandProd": 75,
      "IsFullBlast": true,
      "CanStart": true,
      "LoadPercentage": 1,
      "ProdPowerComsumption": 0,
      "CurrentPotential": 1,
      "ProductionCapacity": 75,
      "DefaultProductionCapacity": 75,
      "PowerProductionPotential": 75,
      "FuelAmount": 0.79486042261123657,
      "NuclearWarning": "EGeneratorNuclearWarning::GNW_None",
      "FuelResource": "EResourceForm::RF_SOLID",
      "GeoMinPower": 0,
      "GeoMaxPower": 0,
      "AvailableFuel": [
         {
            "Name": "Coal",
            "ClassName": "Desc_Coal_C"
         },
         {
            "Name": "Compacted Coal",
            "ClassName": "Desc_CompactedCoal_C"
         },
         {
            "Name": "Petroleum Coke",
            "ClassName": "Desc_PetroleumCoke_C"
         }
      ],
      "WasteInventory": [],
      "features":
      {
         "properties":
         {
            "name": "Coal Generator",
            "type": "Power Generator"
         },
         "geometry":
         {
            "coordinates":
            {
               "X": -98814.7578125,
               "Y": -143888.078125,
               "Z": -808.1903076171875
            },
            "type": "Point"
         }
      }
   },
   {
      "ID": 0,
      "Name": "Fuel Generator",
      "ClassName": "Build_GeneratorFuel_C_2147249129",
      "location":
      {
         "X": -65431.5703125,
         "Y": -179509.546875,
         "Z": 3829.33349609375
      },
      "CircuitID": 58,
      "BaseProd": 0,
      "DynamicProdCapacity": 150,
      "DynamicProdDemandFactor": 1,
      "RegulatedDemandProd": 150,
      "IsFullBlast": true,
      "CanStart": true,
      "LoadPercentage": 1,
      "ProdPowerComsumption": 0,
      "CurrentPotential": 1,
      "ProductionCapacity": 150,
      "DefaultProductionCapacity": 150,
      "PowerProductionPotential": 150,
      "FuelAmount": 0.23114287853240967,
      "NuclearWarning": "EGeneratorNuclearWarning::GNW_None",
      "FuelResource": "EResourceForm::RF_LIQUID",
      "GeoMinPower": 0,
      "GeoMaxPower": 0,
      "AvailableFuel": [
         {
            "Name": "Fuel",
            "ClassName": "Desc_LiquidFuel_C"
         },
         {
            "Name": "Turbofuel",
            "ClassName": "Desc_LiquidTurboFuel_C"
         },
         {
            "Name": "Liquid Biofuel",
            "ClassName": "Desc_LiquidBiofuel_C"
         }
      ],
      "WasteInventory": [],
      "features":
      {
         "properties":
         {
            "name": "Fuel Generator",
            "type": "Power Generator"
         },
         "geometry":
         {
            "coordinates":
            {
               "X": -65431.5703125,
               "Y": -179509.546875,
               "Z": 3829.33349609375
            },
            "type": "Point"
         }
      }
   }
]
-----------------