= Belt Stats/GeoLocation

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

API Endpoint: getBelts +

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|Name
|Pipe Type
|String
|Output

|ClassName
|UE Class Name
|String
|Output

|FluidName
|Fluid/Gas in Pipe
|String
|Output

|location0/x
|X Location of Pipe
|Float
|Output

|location0/y
|Y Location of Pipe
|Float
|Output

|location0/z
|Z Location of Pipe
|Float
|Output

|Connected0
|Is Pipe Connected at starting point?
|Boolean
|Output

|location1/x
|X Location of Pipe
|Float
|Output

|location1/y
|Y Location of Pipe
|Float
|Output

|location1/z
|Z Location of Pipe
|Float
|Output

|Connected1
|Is Belt Connected at starting point?
|Boolean
|Output

|Flow
|Flow Speed
|Float
|Output

|FlowPct
|Flow Speed Percentage
|Float
|Output

|features/properties/name
|Type of name being marked (Player, Train Track(WIP), Notable Building, etc)
|String
|Output

|features/properties/type
|Type of item being marked (Player, Train Track(WIP), Notable Building, etc)
|String
|Output

|features/geometry/name
|GeoJSON name of map marking (Point, Line, Circle, etc)
|String
|Output

|features/geometry/coordinates
|X,Y,Z for map marking
|[Float, Float, Float]
|Output

|features/geometry/type
|GeoJSON type of map marking (Point, Line, Circle, etc)
|String
|Output

|===

Example:
[source,json]
-----------------
[
   {
		"Name": "Pipeline Mk.2",
		"ClassName": "Build_PipelineMK2_C_2146967477",
		"FluidName": "Water",
		"FluidClass": "Desc_Water_C",
		"location0":
		{
			"X": -92593.2890625,
			"Y": -85316.9296875,
			"Z": 4264.8427734375
		},
		"Connected0": true,
		"location1":
		{
			"X": -90623.703125,
			"Y": -84969.46875,
			"Z": 4264.8427734375
		},
		"Connected1": true,
		"Flow": 0.78740155696868896,
		"FlowPct": 0.078740157186985016,
		"features":
		{
			"properties":
			{
				"name": "Pipeline Mk.2",
				"type": "Pipeline Mk.2"
			},
			"geometry":
			{
				"coordinates": [
					{
						"X": -92593.2890625,
						"Y": -85316.9296875,
						"Z": 4264.8427734375
					},
					{
						"X": -90623.703125,
						"Y": -84969.46875,
						"Z": 4264.8427734375
					}
				],
				"type": "Line"
			}
		}
	},
	{
		"Name": "Pipeline Mk.2",
		"ClassName": "Build_PipelineMK2_C_2147016322",
		"FluidName": "Crude Oil",
		"FluidClass": "Desc_LiquidOil_C",
		"location0":
		{
			"X": -49386.03515625,
			"Y": -169084.453125,
			"Z": -335.15765380859375
		},
		"Connected0": true,
		"location1":
		{
			"X": -51749.51953125,
			"Y": -169501.5,
			"Z": -335.15756225585938
		},
		"Connected1": true,
		"Flow": 10,
		"FlowPct": 1,
		"features":
		{
			"properties":
			{
				"name": "Pipeline Mk.2",
				"type": "Pipeline Mk.2"
			},
			"geometry":
			{
				"coordinates": [
					{
						"X": -49386.03515625,
						"Y": -169084.453125,
						"Z": -335.15765380859375
					},
					{
						"X": -51749.51953125,
						"Y": -169501.5,
						"Z": -335.15756225585938
					}
				],
				"type": "Line"
			}
		}
	}
]
-----------------