= Production Stats by Andre Aquila of Aquila Industrial

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

API Endpoint: getProdStats +
Production Stats by Andre Aquila of Aquila Industrial +
Production Stats Mod: https://ficsit.app/mod/3tsvcG3A6gqKX1

Note: If the item is not being produced or extracted, it will not be displayed.

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|Name
|Name of the item mined/extracted/produced
|String
|Output

|ClassName
|UE Class Name
|String
|Output

|ProdPerMin
|Production/Consumption per minute (Format: P: Actual/Max /min - C: Actual/Max /min)
|String
|Output

|ProdPercent
|Efficiency percentage produced
|Float
|Output

|ConsPercent
|Efficiency percentage Consumed
|Float
|Output

|CurrentProd
|Current production
|Float
|Output

|MaxProd
|Maximum production based on machines
|Float
|Output

|CurrentConsumed
|Current consumption
|Float
|Output

|MaxConsumed
|Maximum consumption based on machines
|Float
|Output

|Type
|Denotes how item is transferred. Item on belt, or fluid/gas on pipe
|String
|Output

|===

Example:
[source,json]
-----------------
[
	{
		"Name": "Alclad Aluminum Sheet",
		"ClassName": "Desc_AluminumPlate_C",
		"ProdPerMin": "P:0.0/min - C: 0.0/min",
		"ProdPercent": 0,
		"ConsPercent": 0,
		"CurrentProd": 0,
		"MaxProd": 240,
		"CurrentConsumed": 0,
		"MaxConsumed": 89.999992370605469,
		"Type": "Belt"
	},
	{
		"Name": "Alumina Solution",
		"ClassName": "Desc_AluminaSolution_C",
		"ProdPerMin": "P:0.0/min - C: 0.0/min",
		"ProdPercent": 0,
		"ConsPercent": 0,
		"CurrentProd": 0,
		"MaxProd": 720.00006103515625,
		"CurrentConsumed": 0,
		"MaxConsumed": 660,
		"Type": "Pipe"
	},
	{
		"Name": "Aluminum Casing",
		"ClassName": "Desc_AluminumCasing_C",
		"ProdPerMin": "P:0.0/min - C: 0.0/min",
		"ProdPercent": 0,
		"ConsPercent": 0,
		"CurrentProd": 0,
		"MaxProd": 240,
		"CurrentConsumed": 0,
		"MaxConsumed": 180,
		"Type": "Belt"
	}
]
-----------------