= Power Generation/Consumption Stats

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

URI Handler: getPower +

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|CircuitID
|Identification number for the power circuit
|Integer
|Output

|PowerConsumed
|Power consumed on selected power circuit
|Integer
|Output

|PowerCapacity
|Power capacity on selected power circuit
|Integer
|Output
	
|PowerMaxConsumed
|Maximum Power that can be consumed on selected power circuit
|Integer
|Output
	
|BatteryDifferential
|Amount of power in excess/deficit going into or out of the battery bank(s). Positive = Charges batteries, Negative = Drains batteries
|Integer
|Output
	
|BatteryPercent
|Percentage of battery bank(s) charge
|Integer
|Output
	
|BatteryCapacity
|Total capacity of battery bank(s)
|Integer
|Output
	
|BatteryTimeEmpty
|Time (in hh:mm:ss) until Batteries are empty
|Float
|Output
	
|BatteryTimeFull
|Time (in hh:mm:ss) until Batteries are full
|Float
|Output
	
|FuseTriggered
|Has the fuse been triggered
|Boolean (true/false)
|Output

|===

Example:
[source,json]
-----------------
[{
      "CircuitID":58,
      "PowerCapacity":8065.0,
      "PowerProduction":8005.0,
      "PowerConsumed":7086.0,
      "PowerMaxConsumed":9260.0,
      "BatteryDifferential":0.0,
      "BatteryPercent":100.0,
      "BatteryCapacity":2500,
      "BatteryTimeEmpty":"00:00:00",
      "BatteryTimeFull":"00:00:00",
      "FuseTriggered":false
},{
      "CircuitID":9,
      "PowerCapacity":8065.0,
      "PowerProduction":8005.0,
      "PowerConsumed":7086.0,
      "PowerMaxConsumed":9260.0,
      "BatteryDifferential":0.0,
      "BatteryPercent":100.0,
      "BatteryCapacity":2500,
      "BatteryTimeEmpty":"00:00:00",
      "BatteryTimeFull":"00:00:00",
      "FuseTriggered":false
}]
-----------------