= Schematics Status

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

API Endpoint: getSchematics +

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|RecipeName
|Name of Recipe Associated with Schematic/Milestone
|String
|Output

|Category
|Recipe Category
|String
|Output

|Events/Name
|Special Event Name, if applicable, for recipe
|String
|Output

|Ingredients/Name
|Name of items needed for Recipe
|String
|Output

|Ingredients/ClassName
|UE Class Name
|String
|Output

|Ingredients/Amount
|Amount of items required for recipe
|Integar
|Output

|Ingredients/ManualRate
|Rate per minute, the items manual processing requires at 100% throughput
|Float
|Output

|Ingredients/FactoryRate
|Rate per minute, the items automated processing requires at 100% throughput
|Float
|Output

|Products/Name
|Name of items produced for Recipe
|String
|Output

|Products/ClassName
|UE Class Name
|String
|Output

|Products/Amount
|Amount of items produced for recipe
|Integar
|Output

|Products/ManualRate
|Rate per minute, the items manual processing produces at 100% throughput
|Float
|Output

|Products/FactoryRate
|Rate per minute, the items automated processing produces at 100% throughput
|Float
|Output

|ProducedIn/ProducedIn
|Build tool/factory building used to create item
|String
|Output

|ManualDuration
|Name of Item Associated with Schematic/Milestone
|String
|Output

|ManufacturingDuration
|Name of Item Associated with Schematic/Milestone
|String
|Output

|===

Example:
[source,json]
-----------------
[
   {
   "Name": "Wall Signs",
   "TechTier": 1,
   "Type": 6.1552420141504922e+17,
   "Recipes": [
      {
         "RecipeName": "Wall Holo Sign 1x1",
         "Category": "N/A",
         "Events": [],
         "Ingredients": [
            {
               "Name": "Iron Plate",
               "ClassName": "Desc_IronPlate_C",
               "Amount": 3,
               "ManualRate": 180,
               "FactoryRate": 180
            },
            {
               "Name": "Iron Rod",
               "ClassName": "Desc_IronRod_C",
               "Amount": 4,
               "ManualRate": 240,
               "FactoryRate": 240
            },
            {
               "Name": "Screw",
               "ClassName": "Desc_IronScrew_C",
               "Amount": 4,
               "ManualRate": 240,
               "FactoryRate": 240
            },
            {
               "Name": "Quickwire",
               "ClassName": "Desc_HighSpeedWire_C",
               "Amount": 10,
               "ManualRate": 600,
               "FactoryRate": 600
            },
            {
               "Name": "Quartz Crystal",
               "ClassName": "Desc_QuartzCrystal_C",
               "Amount": 3,
               "ManualRate": 180,
               "FactoryRate": 180
            }
         ],
         "Products": [
            {
               "Name": "Wall Holo Sign 1x1",
               "ClassName": "Desc_RSS_Holoscreen_1x1_C",
               "Amount": 1,
               "ManualRate": 60,
               "FactoryRate": 60
            }
         ],
         "ProducedIn": [
            {
               "ProducedIn": "Build Gun"
            }
         ],
         "ManualDuration": 1,
         "ManufacturingDuration": 1
      },
      {
         "RecipeName": "Wall Holo Sign 1x2",
         "Category": "N/A",
         "Events": [],
         "Ingredients": [
            {
               "Name": "Iron Plate",
               "ClassName": "Desc_IronPlate_C",
               "Amount": 3,
               "ManualRate": 180,
               "FactoryRate": 180
            },
            {
               "Name": "Iron Rod",
               "ClassName": "Desc_IronRod_C",
               "Amount": 4,
               "ManualRate": 240,
               "FactoryRate": 240
            },
            {
               "Name": "Screw",
               "ClassName": "Desc_IronScrew_C",
               "Amount": 4,
               "ManualRate": 240,
               "FactoryRate": 240
            },
            {
               "Name": "Quickwire",
               "ClassName": "Desc_HighSpeedWire_C",
               "Amount": 10,
               "ManualRate": 600,
               "FactoryRate": 600
            },
            {
               "Name": "Quartz Crystal",
               "ClassName": "Desc_QuartzCrystal_C",
               "Amount": 3,
               "ManualRate": 180,
               "FactoryRate": 180
            }
         ],
         "Products": [
            {
               "Name": "Wall Holo Sign 1x2",
               "ClassName": "Desc_RSS_Holoscreen_1x2_C",
               "Amount": 1,
               "ManualRate": 60,
               "FactoryRate": 60
            }
         ],
         "ProducedIn": [
            {
               "ProducedIn": "Build Gun"
            }
         ],
         "ManualDuration": 1,
         "ManufacturingDuration": 1
      },
      {
         "RecipeName": "Wall Holo Sign 2x1",
         "Category": "N/A",
         "Events": [],
         "Ingredients": [
            {
               "Name": "Iron Plate",
               "ClassName": "Desc_IronPlate_C",
               "Amount": 3,
               "ManualRate": 180,
               "FactoryRate": 180
            },
            {
               "Name": "Iron Rod",
               "ClassName": "Desc_IronRod_C",
               "Amount": 4,
               "ManualRate": 240,
               "FactoryRate": 240
            },
            {
               "Name": "Screw",
               "ClassName": "Desc_IronScrew_C",
               "Amount": 4,
               "ManualRate": 240,
               "FactoryRate": 240
            },
            {
               "Name": "Quickwire",
               "ClassName": "Desc_HighSpeedWire_C",
               "Amount": 10,
               "ManualRate": 600,
               "FactoryRate": 600
            },
            {
               "Name": "Quartz Crystal",
               "ClassName": "Desc_QuartzCrystal_C",
               "Amount": 3,
               "ManualRate": 180,
               "FactoryRate": 180
            }
         ],
         "Products": [
            {
               "Name": "Wall Holo Sign 2x1",
               "ClassName": "Desc_RSS_holoscreen_2x1_C",
               "Amount": 1,
               "ManualRate": 60,
               "FactoryRate": 60
            }
         ],
         "ProducedIn": [
            {
               "ProducedIn": "Build Gun"
            }
         ],
         "ManualDuration": 1,
         "ManufacturingDuration": 1
      },
      {
         "RecipeName": "Wall Sign 7x1",
         "Category": "N/A",
         "Events": [],
         "Ingredients": [
            {
               "Name": "Iron Plate",
               "ClassName": "Desc_IronPlate_C",
               "Amount": 3,
               "ManualRate": 180,
               "FactoryRate": 180
            },
            {
               "Name": "Iron Rod",
               "ClassName": "Desc_IronRod_C",
               "Amount": 4,
               "ManualRate": 240,
               "FactoryRate": 240
            },
            {
               "Name": "Screw",
               "ClassName": "Desc_IronScrew_C",
               "Amount": 4,
               "ManualRate": 240,
               "FactoryRate": 240
            },
            {
               "Name": "Quickwire",
               "ClassName": "Desc_HighSpeedWire_C",
               "Amount": 10,
               "ManualRate": 600,
               "FactoryRate": 600
            },
            {
               "Name": "Quartz Crystal",
               "ClassName": "Desc_QuartzCrystal_C",
               "Amount": 3,
               "ManualRate": 180,
               "FactoryRate": 180
            }
         ],
         "Products": [
            {
               "Name": "Wall Sign 7x1",
               "ClassName": "Desc_RSS_Holoscreen_7x1_C",
               "Amount": 1,
               "ManualRate": 60,
               "FactoryRate": 60
            }
         ],
         "ProducedIn": [
            {
               "ProducedIn": "Build Gun"
            }
         ],
         "ManualDuration": 1,
         "ManufacturingDuration": 1
      }
   ],
   "Locked": false,
   "Purchased": false,
   "DepLocked": false
}
]
-----------------