= Production Stats by Andre Aquila of Aquila Industrial

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

URI Handler: getProdStats +
Production Stats by Andre Aquila of Aquila Industrial +
Production Stats Mod: https://ficsit.app/mod/3tsvcG3A6gqKX1

Note: If the item is not being produced or extracted, it will not be displayed.

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|ItemName
|Name of the item mined/extracted/produced
|String
|Output

|ProdPerMin
|Production/Consumption per minute (Format: P: Actual/Max /min - C: Actual/Max /min)
|String
|Output

|ProdPercent
|Efficiency percentage produced
|Float
|Output

|ConsPercent
|Efficiency percentage Consumed
|Float
|Output

|Type
|Denotes how item is transferred. Item on belt, or fluid/gas on pipe
|String
|Output

|CurrentProd
|Current production
|Float
|Output

|MaxProd
|Maximum production based on machines
|Float
|Output

|CurrentConsumed
|Current consumption
|Float
|Output

|MaxConsumed
|Maximum consumption based on machines
|Float
|Output

|===

Example:
[source,json]
-----------------
[{
      "ItemName":"Actual Snow",
      "ProdPerMin":"P: 30.0/30.0/min - C: 0.0/30.0/min",
      "ProdPercent":99.610001,
      "ConsPercent":0.0,
      "CurrentProd":30.0,
      "MaxProd":30.0,
      "CurrentConsumed":0.0,
      "MaxConsumed":30.0,
      "Type":"Belt"
}, {
      "ItemName":"AI Limiter",
      "ProdPerMin":"P: 5.0/5.0/min - C: 0.0/8.0/min",
      "ProdPercent":100.0,
      "ConsPercent":0.0,
      "CurrentProd":5.0,
      "MaxProd":5.0,
      "CurrentConsumed":0.0,
      "MaxConsumed":8.0,
      "Type":"Belt"
}]
-----------------