= Resource Node Stats

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

API Endpoint: +
getResourceNode - Mining/Oil +
getResourceGeyser - Geothermal Geyser +
getResourceWell - Fracking/Resource Well +

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|Name
|Node Name
|String
|Output

|ClassName
|UE Class Name
|String
|Output

|location/x
|X Location of Resource Node
|Float
|Output

|location/y
|Y Location of Resource Node
|Float
|Output

|location/z
|Z Location of Resource Node
|Float
|Output

|EnumPurity
|Enum Purity of Resource Node
|String
|Output

|Purity
|Purity of Resource Node
|String
|Output

|NodeType
|Resource Node Type
|Integer
|Output

|Exploited
|Is the Resource being extracted
|Boolean
|Output

|features/properties/name
|Type of name being marked (Player, Train Track(WIP), Notable Building, etc)
|String
|Output

|features/properties/type
|Type of item being marked (Player, Train Track(WIP), Notable Building, etc)
|String
|Output

|features/geometry/name
|GeoJSON name of map marking (Point, Line, Circle, etc)
|String
|Output

|features/geometry/coordinates
|X,Y,Z for map marking
|[Float, Float, Float]
|Output

|features/geometry/type
|GeoJSON type of map marking (Point, Line, Circle, etc)
|String
|Output

|===

Example:
[source,json]
-----------------
[
	{
		"Name": "Raw Quartz",
		"ClassName": "",
		"location":
		{
			"X": -24911.302734375,
			"Y": -142186.59375,
			"Z": 8143.46875
		},
		"EnumPurity": "Pure",
		"Purity": "Pure",
		"NodeType": "Node",
		"Exploited": false,
		"features":
		{
			"properties":
			{
				"name": "Raw Quartz",
				"type": "Resource Node"
			},
			"geometry":
			{
				"coordinates":
				{
					"X": -24911.302734375,
					"Y": -142186.59375,
					"Z": 8143.46875
				},
				"type": "Point"
			}
		}
	},
	{
		"Name": "Copper Ore",
		"ClassName": "",
		"location":
		{
			"X": -21028.134765625,
			"Y": -137929.515625,
			"Z": 10295.291015625
		},
		"EnumPurity": "Pure",
		"Purity": "Pure",
		"NodeType": "Node",
		"Exploited": false,
		"features":
		{
			"properties":
			{
				"name": "Copper Ore",
				"type": "Resource Node"
			},
			"geometry":
			{
				"coordinates":
				{
					"X": -21028.134765625,
					"Y": -137929.515625,
					"Z": 10295.291015625
				},
				"type": "Point"
			}
		}
	}
]
-----------------