= Radar Tower Information

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

API Endpoint: getRadarTower +

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|Name
|Tower Name
|String
|Output

|ClassName
|UE Class Name
|String
|Output

|location/x
|X Location of Slug
|Float
|Output

|location/y
|Y Location of Slug
|Float
|Output

|location/z
|Z Location of Slug
|Float
|Output

|location/Rotation
|Compass Heading of Slug
|Float
|Output

|Fauna/Name
|Fauna's Name
|String
|Output

|Fauna/ClassName
|UE Class Name
|String
|Output

|Fauna/Remaining
|Fauna Remaining
|Integer
|Output

|Signal/Name
|Name of Object scanned
|String
|Output

|Signal/ClassName
|UE Class Name
|String
|Output

|Signal/Remaining
|Signal Remaining
|Integer
|Output

|Flora/Name
|Flora's Name
|String
|Output

|Flora/ClassName
|UE Class Name
|String
|Output

|Flora/Remaining
|Flora Remaining
|Integer
|Output

|===

Example:
[source,json]
-----------------
[
	{
		"Name": "Radar Tower",
		"ClassName": "Build_RadarTower_C_2147374116",
		"location":
		{
			"X": -64181.77734375,
			"Y": -138709.890625,
			"Z": 10639.4453125
		},
		"Fauna": [
			{
				"Name": "Small Desert Spitter",
				"ClassName": "Desc_SpitterDesert_Small_C",
				"Remaining": 1
			},
			{
				"Name": "Fluffy-tailed Hog",
				"ClassName": "Desc_HogBasic_C",
				"Remaining": 1
			},
			{
				"Name": "Non-flying Birb",
				"ClassName": "Desc_NonflyingBird_C",
				"Remaining": 1
			},
			{
				"Name": "Alpha Forest Spitter",
				"ClassName": "Desc_SpitterForest_Alpha_C",
				"Remaining": 1
			},
			{
				"Name": "Unknown File Error #6265616e",
				"ClassName": "Desc_SpaceGiraffe_C",
				"Remaining": 1
			},
			{
				"Name": "Lizard Doggo",
				"ClassName": "Desc_SpaceRabbit_C",
				"Remaining": 1
			},
			{
				"Name": "Small Forest Spitter",
				"ClassName": "Desc_SpitterForest_Small_C",
				"Remaining": 1
			},
			{
				"Name": "Alpha Stinger",
				"ClassName": "Desc_StingerAlpha_C",
				"Remaining": 1
			},
			{
				"Name": "Small Stinger",
				"ClassName": "Desc_StingerSmall_C",
				"Remaining": 1
			},
			{
				"Name": "Small Aquatic Spitter",
				"ClassName": "Desc_SpitterAquatic_Small_C",
				"Remaining": 1
			},
			{
				"Name": "Alpha Hog",
				"ClassName": "Desc_HogAlpha_C",
				"Remaining": 1
			},
			{
				"Name": "Alpha Desert Spitter",
				"ClassName": "Desc_SpitterDesert_Alpha_C",
				"Remaining": 1
			}
		],
		"Signal": [
			{
				"Name": "Somersloop WIP",
				"ClassName": "Desc_WAT1_C",
				"Remaining": 13
			},
			{
				"Name": "Blue Power Slug",
				"ClassName": "Desc_Crystal_C",
				"Remaining": 59
			},
			{
				"Name": "Mercer Sphere WIP",
				"ClassName": "Desc_WAT2_C",
				"Remaining": 10
			},
			{
				"Name": "Hard Drive",
				"ClassName": "Desc_HardDrive_C",
				"Remaining": 1
			}
		],
		"Flora": [
			{
				"Name": "Berry Bush Plant",
				"ClassName": "Desc_BerryBush_C",
				"Remaining": 1
			},
			{
				"Name": "Nut Bush Plant",
				"ClassName": "Desc_NutBush_C",
				"Remaining": 1
			},
			{
				"Name": "Bacon Agaric",
				"ClassName": "Desc_Shroom_C",
				"Remaining": 1
			}
		],
		"features":
		{
			"properties":
			{
				"name": "Radar Tower",
				"type": "Radar Tower"
			},
			"geometry":
			{
				"coordinates":
				{
					"X": -64181.77734375,
					"Y": -138709.890625,
					"Z": 10639.4453125
				},
				"type": "Point"
			}
		}
	}
]
-----------------