= Power Switch Status

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

API Endpoint: getSwitches +

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|Name
|Name
|String
|Output

|ClassName
|UE Class Name
|String
|Output

|location/x
|X Location of Storage Container
|Float
|Output

|location/y
|Y Location of Storage Container
|Float
|Output

|location/z
|Z Location of Storage Container
|Float
|Output

|location/Rotation
|Compass Heading of Storage Container
|Float
|Output

|SwitchTag
|Name Tag for Power Switch
|String
|Output

|Connected
|Is Connected
|Boolean
|Output

|IsOn
|Is the Switch On
|Boolean
|Output

|Primary
|Primary Circuit Connection ID
|Integer
|Output

|Secondary
|Secondary Circuit Connection ID
|Integer
|Output

|features/properties/name
|Type of name being marked (Player, Train Track(WIP), Notable Building, etc)
|String
|Output

|features/properties/type
|Type of item being marked (Player, Train Track(WIP), Notable Building, etc)
|String
|Output

|features/geometry/name
|GeoJSON name of map marking (Point, Line, Circle, etc)
|String
|Output

|features/geometry/coordinates
|X,Y,Z for map marking
|[Float, Float, Float]
|Output

|features/geometry/type
|GeoJSON type of map marking (Point, Line, Circle, etc)
|String
|Output

|===

Example:
[source,json]
-----------------
[
      {
            "Name": "Power Switch",
            "ClassName": "Build_PowerSwitch_C_2147265249",
            "location":
            {
                  "x": -64296.85546875,
                  "y": -172629.515625,
                  "z": 289.84228515625,
                  "rotation": 280
            },
            "SwitchTag": "Oil Tower",
            "Connected": true,
            "IsOn": true,
            "Primary": 58,
            "Secondary": 44,
            "features":
            {
                  "properties":
                  {
                        "name": "Oil Tower",
                        "type": "Power Switch"
                  },
                  "geometry":
                  {
                        "coordinates":
                        {
                              "X": -64296.85546875,
                              "Y": -172629.515625,
                              "Z": 289.84228515625
                        },
                        "type": "Point"
                  }
            }
      },
      {
            "Name": "Power Switch",
            "ClassName": "Build_PowerSwitch_C_2147144997",
            "location":
            {
                  "x": -66175.734375,
                  "y": -125134.0625,
                  "z": 3789.84228515625,
                  "rotation": 190
            },
            "SwitchTag": "Steel Prodution",
            "Connected": true,
            "IsOn": true,
            "Primary": 44,
            "Secondary": 5,
            "features":
            {
                  "properties":
                  {
                        "name": "Steel Prodution",
                        "type": "Power Switch"
                  },
                  "geometry":
                  {
                        "coordinates":
                        {
                              "X": -66175.734375,
                              "Y": -125134.0625,
                              "Z": 3789.84228515625
                        },
                        "type": "Point"
                  }
            }
      }
]
-----------------