= Inventory of Storage Containers

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

API Endpoint: getStorageInv +

This is inventory of the world broken up by their storage containers. This does not include pipes/belts/factory buildings, only buildings whom purpose is to provide storage except Fluid Buffers.

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|building
|Name of Storage Container type
|String
|Output

|ClassName
|UE Class Name
|String
|Output

|location/x
|X Location of Storage Container
|Float
|Output

|location/y
|Y Location of Storage Container
|Float
|Output

|location/z
|Z Location of Storage Container
|Float
|Output

|location/Rotation
|Compass Heading of Storage Container
|Float
|Output

|inventory/Name
|Name of item type
|String
|Output

|inventory/ClassName
|Class Name of item type
|String
|Output

|inventory/Amount
|Amount of items of item type
|Integar
|Output

|features/properties/name
|Type of name being marked (Player, Train Track(WIP), Notable Building, etc)
|String
|Output

|features/properties/type
|Type of item being marked (Player, Train Track(WIP), Notable Building, etc)
|String
|Output

|features/geometry/name
|GeoJSON name of map marking (Point, Line, Circle, etc)
|String
|Output

|features/geometry/coordinates
|X,Y,Z for map marking
|[Float, Float, Float]
|Output

|features/geometry/type
|GeoJSON type of map marking (Point, Line, Circle, etc)
|String
|Output

|===

Example:
[source,json]
-----------------
[
   {
      "Name": "Storage Container",
      "ClassName": "Build_StorageContainerMk1_C_49",
      "location":
      {
         "x": -105405.53125,
         "y": -130123.4453125,
         "z": 189.8421630859375,
         "rotation": 100
      },
      "inventory": [
         {
            "Name": "Snowball",
            "ClassName": "Desc_SnowballProjectile_C",
            "Amount": 500
         }
      ],
      "features":
      {
         "properties":
         {
            "name": "Storage Container",
            "type": "Storage Container"
         },
         "geometry":
         {
            "coordinates":
            {
               "X": -105405.53125,
               "Y": -130123.4453125,
               "Z": 189.8421630859375
            },
            "type": "Point"
         }
      }
   },
   {
      "Name": "Storage Container",
      "ClassName": "Build_StorageContainerMk1_C_51",
      "location":
      {
         "x": -104420.7265625,
         "y": -129949.7890625,
         "z": 189.84228515625,
         "rotation": 100
      },
      "inventory": [
         {
            "Name": "Snowball",
            "ClassName": "Desc_SnowballProjectile_C",
            "Amount": 500
         }
      ],
      "features":
      {
         "properties":
         {
            "name": "Storage Container",
            "type": "Storage Container"
         },
         "geometry":
         {
            "coordinates":
            {
               "X": -104420.7265625,
               "Y": -129949.7890625,
               "Z": 189.84228515625
            },
            "type": "Point"
         }
      }
   }
]
-----------------