= Schematics Status

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

API Endpoint: getSchematics +

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|SchematicName
|Schematic/Milestone Name
|String
|Output

|TechTier
|Tech Tier
|Integer
|Output

|Type
|Schematic/Milestone Type
|String
|Output

|Recipes/RecipeName
|Name of Recipe Associated with Schematic/Milestone
|String
|Output

|Recipes/Category
|Recipe Category
|String
|Output

|Recipes/Events/Name
|Special Event Name, if applicable, for recipe
|String
|Output

|Recipes/Ingredients/Name
|Name of items needed for Recipe
|String
|Output

|Recipes/Ingredients/ClassName
|UE Class Name
|String
|Output

|Recipes/Ingredients/Amount
|Amount of items required for recipe
|Integar
|Output

|Recipes/Ingredients/ManualRate
|Rate per minute, the items manual processing requires at 100% throughput
|Float
|Output

|Recipes/Ingredients/FactoryRate
|Rate per minute, the items automated processing requires at 100% throughput
|Float
|Output

|Recipes/Products/Name
|Name of items produced for Recipe
|String
|Output

|Recipes/Products/ClassName
|UE Class Name
|String
|Output

|Recipes/Products/Amount
|Amount of items produced for recipe
|Integar
|Output

|Recipes/Products/ManualRate
|Rate per minute, the items manual processing produces at 100% throughput
|Float
|Output

|Recipes/Products/FactoryRate
|Rate per minute, the items automated processing produces at 100% throughput
|Float
|Output

|Recipes/ProducedIn/ProducedIn
|Build tool/factory building used to create item
|String
|Output

|Recipes/ManualDuration
|Name of Item Associated with Schematic/Milestone
|String
|Output

|Recipes/ManufacturingDuration
|Name of Item Associated with Schematic/Milestone
|String
|Output

|Locked
|Is the Schematic/Milestone Locked (Unsure of what CSS Defines)
|Boolean
|Output

|Purchased
|Is Schematic/Milestone Purchased
|Boolean
|Output

|DepLocked
|Dependency Lock for Schematic/Milestone
|Boolean
|Output

|===

Example:
[source,json]
-----------------
[
   {
   "SchematicName": "Wall Signs",
   "TechTier": 1,
   "Type": 6.1552420141504922e+17,
   "Recipes": [
      {
         "RecipeName": "Wall Holo Sign 1x1",
         "Category": "N/A",
         "Events": [],
         "Ingredients": [
            {
               "Name": "Iron Plate",
               "ClassName": "Desc_IronPlate_C",
               "Amount": 3,
               "ManualRate": 180,
               "FactoryRate": 180
            },
            {
               "Name": "Iron Rod",
               "ClassName": "Desc_IronRod_C",
               "Amount": 4,
               "ManualRate": 240,
               "FactoryRate": 240
            },
            {
               "Name": "Screw",
               "ClassName": "Desc_IronScrew_C",
               "Amount": 4,
               "ManualRate": 240,
               "FactoryRate": 240
            },
            {
               "Name": "Quickwire",
               "ClassName": "Desc_HighSpeedWire_C",
               "Amount": 10,
               "ManualRate": 600,
               "FactoryRate": 600
            },
            {
               "Name": "Quartz Crystal",
               "ClassName": "Desc_QuartzCrystal_C",
               "Amount": 3,
               "ManualRate": 180,
               "FactoryRate": 180
            }
         ],
         "Products": [
            {
               "Name": "Wall Holo Sign 1x1",
               "ClassName": "Desc_RSS_Holoscreen_1x1_C",
               "Amount": 1,
               "ManualRate": 60,
               "FactoryRate": 60
            }
         ],
         "ProducedIn": [
            {
               "ProducedIn": "Build Gun"
            }
         ],
         "ManualDuration": 1,
         "ManufacturingDuration": 1
      },
      {
         "RecipeName": "Wall Holo Sign 1x2",
         "Category": "N/A",
         "Events": [],
         "Ingredients": [
            {
               "Name": "Iron Plate",
               "ClassName": "Desc_IronPlate_C",
               "Amount": 3,
               "ManualRate": 180,
               "FactoryRate": 180
            },
            {
               "Name": "Iron Rod",
               "ClassName": "Desc_IronRod_C",
               "Amount": 4,
               "ManualRate": 240,
               "FactoryRate": 240
            },
            {
               "Name": "Screw",
               "ClassName": "Desc_IronScrew_C",
               "Amount": 4,
               "ManualRate": 240,
               "FactoryRate": 240
            },
            {
               "Name": "Quickwire",
               "ClassName": "Desc_HighSpeedWire_C",
               "Amount": 10,
               "ManualRate": 600,
               "FactoryRate": 600
            },
            {
               "Name": "Quartz Crystal",
               "ClassName": "Desc_QuartzCrystal_C",
               "Amount": 3,
               "ManualRate": 180,
               "FactoryRate": 180
            }
         ],
         "Products": [
            {
               "Name": "Wall Holo Sign 1x2",
               "ClassName": "Desc_RSS_Holoscreen_1x2_C",
               "Amount": 1,
               "ManualRate": 60,
               "FactoryRate": 60
            }
         ],
         "ProducedIn": [
            {
               "ProducedIn": "Build Gun"
            }
         ],
         "ManualDuration": 1,
         "ManufacturingDuration": 1
      },
      {
         "RecipeName": "Wall Holo Sign 2x1",
         "Category": "N/A",
         "Events": [],
         "Ingredients": [
            {
               "Name": "Iron Plate",
               "ClassName": "Desc_IronPlate_C",
               "Amount": 3,
               "ManualRate": 180,
               "FactoryRate": 180
            },
            {
               "Name": "Iron Rod",
               "ClassName": "Desc_IronRod_C",
               "Amount": 4,
               "ManualRate": 240,
               "FactoryRate": 240
            },
            {
               "Name": "Screw",
               "ClassName": "Desc_IronScrew_C",
               "Amount": 4,
               "ManualRate": 240,
               "FactoryRate": 240
            },
            {
               "Name": "Quickwire",
               "ClassName": "Desc_HighSpeedWire_C",
               "Amount": 10,
               "ManualRate": 600,
               "FactoryRate": 600
            },
            {
               "Name": "Quartz Crystal",
               "ClassName": "Desc_QuartzCrystal_C",
               "Amount": 3,
               "ManualRate": 180,
               "FactoryRate": 180
            }
         ],
         "Products": [
            {
               "Name": "Wall Holo Sign 2x1",
               "ClassName": "Desc_RSS_holoscreen_2x1_C",
               "Amount": 1,
               "ManualRate": 60,
               "FactoryRate": 60
            }
         ],
         "ProducedIn": [
            {
               "ProducedIn": "Build Gun"
            }
         ],
         "ManualDuration": 1,
         "ManufacturingDuration": 1
      },
      {
         "RecipeName": "Wall Sign 7x1",
         "Category": "N/A",
         "Events": [],
         "Ingredients": [
            {
               "Name": "Iron Plate",
               "ClassName": "Desc_IronPlate_C",
               "Amount": 3,
               "ManualRate": 180,
               "FactoryRate": 180
            },
            {
               "Name": "Iron Rod",
               "ClassName": "Desc_IronRod_C",
               "Amount": 4,
               "ManualRate": 240,
               "FactoryRate": 240
            },
            {
               "Name": "Screw",
               "ClassName": "Desc_IronScrew_C",
               "Amount": 4,
               "ManualRate": 240,
               "FactoryRate": 240
            },
            {
               "Name": "Quickwire",
               "ClassName": "Desc_HighSpeedWire_C",
               "Amount": 10,
               "ManualRate": 600,
               "FactoryRate": 600
            },
            {
               "Name": "Quartz Crystal",
               "ClassName": "Desc_QuartzCrystal_C",
               "Amount": 3,
               "ManualRate": 180,
               "FactoryRate": 180
            }
         ],
         "Products": [
            {
               "Name": "Wall Sign 7x1",
               "ClassName": "Desc_RSS_Holoscreen_7x1_C",
               "Amount": 1,
               "ManualRate": 60,
               "FactoryRate": 60
            }
         ],
         "ProducedIn": [
            {
               "ProducedIn": "Build Gun"
            }
         ],
         "ManualDuration": 1,
         "ManufacturingDuration": 1
      }
   ],
   "Locked": false,
   "Purchased": false,
   "DepLocked": false
}
]
-----------------