= Schematics Status

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

API Endpoint: getSchematics +

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|SchematicName
|Schematic/Milestone Name
|String
|Output

|TechTier
|Tech Tier
|Integer
|Output

|Type
|Schematic/Milestone Type
|String
|Output

|Recipes/RecipeName
|Name of Recipe Associated with Schematic/Milestone
|String
|Output

|Recipes/Category
|Recipe Category
|String
|Output

|Recipes/Events/Name
|Special Event Name, if applicable, for recipe
|String
|Output

|Recipes/Ingredients/Name
|Name of items needed for Recipe
|String
|Output

|Recipes/Ingredients/Amount
|Amount of items required for recipe
|Integar
|Output

|Recipes/Ingredients/ManualRate
|Rate per minute, the items manual processing requires at 100% throughput
|Float
|Output

|Recipes/Ingredients/FactoryRate
|Rate per minute, the items automated processing requires at 100% throughput
|Float
|Output

|Recipes/Products/Name
|Name of items produced for Recipe
|String
|Output

|Recipes/Products/Amount
|Amount of items produced for recipe
|Integar
|Output

|Recipes/Products/ManualRate
|Rate per minute, the items manual processing produces at 100% throughput
|Float
|Output

|Recipes/Products/FactoryRate
|Rate per minute, the items automated processing produces at 100% throughput
|Float
|Output

|Recipes/ProducedIn/ProducedIn
|Build tool/factory building used to create item
|String
|Output

|Recipes/ManualDuration
|Name of Item Associated with Schematic/Milestone
|String
|Output

|Recipes/ManufacturingDuration
|Name of Item Associated with Schematic/Milestone
|String
|Output

|Locked
|Is the Schematic/Milestone Locked (Unsure of what CSS Defines)
|Boolean
|Output

|Purchased
|Is Schematic/Milestone Purchased
|Boolean
|Output

|DepLocked
|Dependency Lock for Schematic/Milestone
|Boolean
|Output

|===

Example:
[source,json]
-----------------
[
   {
      "SchematicName":"Alternate: Polymer Resin",
      "TechTier":0,
      "Type":"Alternate",
      "Recipes":[
         {
            "RecipeName":"Alternate: Polymer Resin",
            "Category":"Oil Products",
            "Events":[
               
            ],
            "Ingredients":[
               {
                  "Name":"Crude Oil",
                  "Amount":6
               }
            ],
            "Products":[
               {
                  "Name":"Polymer Resin",
                  "Amount":13
               },
               {
                  "Name":"Heavy Oil Residue",
                  "Amount":2
               }
            ],
            "ProducedIn":[
               {
                  "BuildTool":"Refinery"
               }
            ],
            "ManualDuration":6,
            "ManufacturingDuration":6
         }
      ],
      "Locked":true,
      "Purchased":true,
      "DepLocked":false
   },
   {
      "SchematicName":"Alternate: Pure Aluminum Ingot",
      "TechTier":0,
      "Type":"Alternate",
      "Recipes":[
         {
            "RecipeName":"Alternate: Pure Aluminum Ingot",
            "Category":"Ingots",
            "Events":[
               
            ],
            "Ingredients":[
               {
                  "Name":"Aluminum Scrap",
                  "Amount":2
               }
            ],
            "Products":[
               {
                  "Name":"Aluminum Ingot",
                  "Amount":1
               }
            ],
            "ProducedIn":[
               {
                  "BuildTool":"Smelter"
               }
            ],
            "ManualDuration":2,
            "ManufacturingDuration":2
         }
      ],
      "Locked":true,
      "Purchased":true,
      "DepLocked":false
   }
]
-----------------