= Train Station Stats 

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

URI Handler: getTrainStation +

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|StationName
|Name of the Station
|Integer
|Output

|location/x
|X Location of Station
|Float
|Output

|location/y
|Y Location of Station
|Float
|Output

|location/z
|Z Location of Station
|Float
|Output

|location/Rotation
|Compass Heading of Station
|Float
|Output

|TransferRate
|Rate of solid items transferring at the station
|Float
|Output

|InflowRate
|Rate of fluids incoming to the station
|Float
|Output

|OutflowRate
|Rate of fluids outgoing from the station
|Float
|Output

|LoadMode
|Load/Unload Mode Set
|String
|Output

|LoadingStatus
|Idle/Loading/Unloading
|String
|Output

|DockingStatus
|Status of Station (Idle/Loading/Unloading)
|String
|Output

|===

Example:
[source,json]
-----------------
[
   {
      "StationName":"Caterium Ore",
      "location":{
         "x":-15742.418945,
         "y":-110549.765625,
         "z":10589.841797,
         "rotation":100
      },
      "TransferRate":6.0,
      "InflowRate":0.0,
      "OutflowRate":0.0,
      "LoadingMode":"Loading",
      "LoadingStatus":"Loading",
      "DockingStatus":"ETPDS_Loading",
      "features":{
         "properties":{
            "type":"Train Station"
         },
         "geometry":{
            "coordinates":{
               "x":-15742.418945,
               "y":-110549.765625,
               "z":10589.841797
            },
            "type":"Point"
         }
      }
   },
   {
      "StationName":"Quickwire Central",
      "location":{
         "x":-41261.640625,
         "y":-134549.375,
         "z":8189.842285,
         "rotation":100
      },
      "TransferRate":0.0,
      "InflowRate":0.0,
      "OutflowRate":0.0,
      "LoadingMode":"Unloading",
      "LoadingStatus":"Idle",
      "DockingStatus":"ETPDS_None",
      "features":{
         "properties":{
            "type":"Train Station"
         },
         "geometry":{
            "coordinates":{
               "x":-41261.640625,
               "y":-134549.375,
               "z":8189.842285
            },
            "type":"Point"
         }
      }
   }
]
-----------------