= Vehicle Station Stats

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

URI Handler: getTruckStation +

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|ID
|ID number of Truck
|Integer
|Output

|StationName
|Name of Vehicle Station
|String
|Output

|location/x
|X Location of Station
|Float
|Output

|location/y
|Y Location of Station
|Float
|Output

|location/z
|Z Location of Station
|Float
|Output

|location/Rotation
|Compass Heading of Station
|Float
|Output

|DockVehicleCount
|# of vehicles docked
|Integer
|Output

|LoadMode
|Load/Unload Mode Set
|String
|Output

|TransferRate
|Rate of item stacks transferred
|Float
|Output

|MaxTransferRate
|Combined Max Stacks/Sec for All Vehicles at station
|Float
|Output

|StationStatus
|Status of Station (Idle/Loading/Unloading)
|String
|Output

|FuelRate
|Amount of fuel used per vehicle
|String
|Output

|FuelType
|Type of fuel stored
|String
|Output

|FuelInventory
|Amount of fuel stored
|Integer
|Output

|StationActivity
|Transferring/Idle
|String
|Output

|Inventory
|Item name in Station
|String
|Output

|InvCount
|# of Item in Station
|Integer
|Output

|===

Example:
[source,json]
-----------------
[
   {
      "ID":"0",
      "StationName":"",
      "location":{
         "x":-88860.914062,
         "y":-128932.007812,
         "z":-1410.142822,
         "rotation":100
      },
      "DockVehicleCount":0,
      "LoadMode":"Loading",
      "TransferRate":0.0,
      "MaxTransferRate":0.0,
      "StationStatus":"IS_ERROR",
      "FuelRate":0.0,
      "FuelType":"N/A",
      "FuelInventory":0,
      "StationActivity":"Idle",
      "Inventory":"N/A",
      "InvCount":0,
      "features":{
         "properties":{
            "type":"Truck Station"
         },
         "geometry":{
            "coordinates":{
               "x":-88860.914062,
               "y":-128932.007812,
               "z":-1410.142822
            },
            "type":"Point"
         }
      }
   }
]
-----------------