= Train Stats 

:url-repo: https://www.github.com/porisius/FicsitRemoteMonitoring

API Endpoint: getTrains +

[cols="1,2,1,1"]
|===
|JSON/JSON Group: |Info: |Data Type: |Input/Output:

|TrainName
|Name of the train
|String
|Output

|location/x
|X Location of Train
|Float
|Output

|location/y
|Y Location of Train
|Float
|Output

|location/z
|Z Location of Train
|Float
|Output

|location/Rotation
|Compass Heading of Train
|Float
|Output

|ForwardSpeed
|Speed in km/h
|Float
|Output

|TotalMass
|(Testing required), total mass of train
|Float
|Output

|PayloadMass
|Payload Mass for Train (More testing required)
|Float
|Output

|PowerConsumed
|Power used by train
|Float
|Output

|TrainStation
|Current or Next Stop for Train
|String
|Output

|ThrottlePercent
|Train's Throttle Setting
|Float
|Output

|Derailed
|Is Derailed
|Boolean
|Output

|PendingDerail
|Has Pending Collision (Name taken from the Object in Unreal)
|Boolean
|Output

|Status
|Status of Train
|String
|Output

|TimeTable/StationName
|Name of Stations in Train's Timetable
|String
|Output

|===

Example:
[source,json]
-----------------
[
   {
      "TrainName":"Caterium Choo",
      "location":{
         "x":-13285.462891,
         "y":-110116.226562,
         "z":10589.841797,
         "rotation":280
      },
      "ForwardSpeed":22.200001,
      "TotalMass":300000.0,
      "PayloadMass":0.0,
      "PowerConsumed":25.0,
      "TrainStation":"Caterium Ore",
      "ThrottlePercent":0.0,
      "Derailed":false,
      "PendingDerail":false,
      "Status":"TS_SelfDriving",
      "TimeTable":[
         {
            "StationName":"Caterium Ore"
         },
         {
            "StationName":"Quickwire Central"
         }
      ],
      "features":{
         "properties":{
            "type":"Train"
         },
         "geometry":{
            "coordinates":{
               "x":-13285.462891,
               "y":-110116.226562,
               "z":10589.841797
            },
            "type":"Point"
         }
      }
   },
   {
      "TrainName":"Elctronics Choo",
      "location":{
         "x":0.0,
         "y":0.0,
         "z":0.0,
         "rotation":90
      },
      "ForwardSpeed":0.0,
      "TotalMass":0.0,
      "PayloadMass":0.0,
      "PowerConsumed":0.0,
      "TrainStation":"Electronics Factory",
      "ThrottlePercent":0.0,
      "Derailed":true,
      "PendingDerail":false,
      "Status":"TS_Derailed",
      "TimeTable":[
         {
            "StationName":"Electronics Factory"
         },
         {
            "StationName":"Aluminum Elctronics"
         }
      ],
      "features":{
         "properties":{
            "type":"Train"
         },
         "geometry":{
            "coordinates":{
               "x":0.0,
               "y":0.0,
               "z":0.0
            },
            "type":"Point"
         }
      }
   }
]
-----------------